[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-rebuild-or-test]
path = "../workspacer-rebuild-or-test"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[package]
edition = "2024"
name = "workspacer-watch-and-reload"
version = "0.1.0"
description = "An asynchronous Rust crate for watching file changes and reloading Rust workspaces and crates. Detects changes in Cargo.toml and src/, executing custom rebuilds or tests."
keywords = ["async", "filesystem", "watch", "rebuild", "reload"]
categories = ["development-tools", "async", "filesystem", "network-programming", "concurrency"]
