[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
version = "0.1.2"

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.1"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.1"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[dependencies.workspacer-rebuild-or-test]
path = "../workspacer-rebuild-or-test"
version = "0.1.1"

[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.1"

[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
version = "0.5.1"

[package]
categories = [
    "development-tools",
    "async",
    "filesystem",
    "network-programming",
    "concurrency",
]
description = "An asynchronous Rust crate for watching file changes and reloading Rust workspaces and crates. Detects changes in Cargo.toml and src/, executing custom rebuilds or tests."
edition = "2024"
keywords = [
    "async",
    "filesystem",
    "watch",
    "rebuild",
    "reload",
]
name = "workspacer-watch-and-reload"
version = "0.1.2"
license = "MIT"
