[dependencies]
derive_builder = "0.20.2"
[dependencies.get-file-size]
path = "../get-file-size"
version = "0.1.0"
[dependencies.serde]
features = [ "derive" ]
version = "*"
[dependencies.serde_derive]
version = "*"
[dependencies.serde_json]
version = "*"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-interface]
path = "../workspacer-interface"
version = "0.5.0"
[dependencies.workspacer-syntax]
path = "../workspacer-syntax"
version = "0.5.0"
[dependencies.workspacer-toml]
path = "../workspacer-toml"
version = "0.5.0"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "Core library for analyzing and extracting the public interface of individual Rust crates as part of the Workspacer suite."
edition = "2024"
license = "MIT OR Apache-2.0"
name = "workspacer-crate"
repository = "https://github.com/klebs6/klebs-general"
version = "0.5.0"