[dependencies.derive_builder]
workspace = true

[dependencies.get-file-size]
path = "../get-file-size"
version = "0.1.1"

[dependencies.serde]
workspace = true

[dependencies.serde_derive]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.sync-run-async]
path = "../sync-run-async"
version = "0.1.1"

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.1"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[dependencies.workspacer-interface]
path = "../workspacer-interface"
version = "0.5.2"

[dependencies.workspacer-syntax]
path = "../workspacer-syntax"
version = "0.5.1"

[dependencies.workspacer-toml]
path = "../workspacer-toml"
version = "0.5.1"

[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
version = "0.1.2"

[package]
authors = ["klebs tpk3.mx@gmail.com"]
categories = [
    "development-tools",
    "asynchronous",
    "filesystem",
    "config",
    "parsing",
]
description = "Efficient management of Rust workspaces with asynchronous operations, offering functionalities for crate initialization, integrity validation, version management, and serialization."
edition = "2024"
keywords = [
    "workspace",
    "async",
    "rust",
]
license = "MIT OR Apache-2.0"
name = "workspacer-crate"
repository = "https://github.com/klebs6/klebs-general"
version = "0.5.1"
