[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[package]
categories = [
    "development-tools",
    "logging",
    "debugging",
    "data-analysis",
]
description = "Enhances tracing and logging capabilities in workspacer applications."
edition = "2024"
keywords = [
    "tracing",
    "workspacer",
    "logging",
    "debugging",
    "monitoring",
]
name = "workspacer-upgrade-tracing"
version = "0.1.1"
license = "MIT"
