[dependencies.tracing]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.2"

[package]
categories = ["development-tools"]
description = "Enhances tracing and logging capabilities in workspacer applications."
edition = "2024"
keywords = [
    "tracing",
    "workspacer",
    "logging",
    "debugging",
    "monitoring",
]
license = "MIT"
name = "workspacer-upgrade-tracing"
version = "0.1.2"
