[dependencies]
workspacer-interface = { version = "0.4.0", path = "../workspacer-interface" }
workspacer-3p        = { version = "0.4.0", path = "../workspacer-3p" }
workspacer-crate     = { version = "0.4.0", path = "../workspacer-crate" }
workspacer-syntax    = { version = "0.4.0", path = "../workspacer-syntax" }

[package]
name        = "workspacer-consolidate"
version     = "0.4.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A utility crate for consolidating a crate's public interface into a single, unified structure."
license     = "MIT OR Apache-2.0"
