[dependencies]
workspacer-interface = "0.1.0"
workspacer-3p        = "0.1.0"
workspacer-crate     = "0.1.0"
workspacer-syntax    = "0.1.0"

[package]
name        = "workspacer-consolidate"
version     = "0.1.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A utility crate for consolidating a crate's public interface into a single, unified structure."
license     = "MIT OR Apache-2.0"
