[[bin]]
name = "workspacer-show-consolidated-crate-interface"
path = "src/bin/show_consolidated_crate_interface.rs"

[dependencies.derive_builder]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_derive]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.structopt]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.1"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.1"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[dependencies.workspacer-interface]
path = "../workspacer-interface"
version = "0.5.2"

[dependencies.workspacer-syntax]
path = "../workspacer-syntax"
version = "0.5.1"

[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.1"

[package]
authors = ["klebs tpk3.mx@gmail.com"]
categories = [
    "development-tools",
    "parsing",
    "asynchronous",
    "api-bindings",
]
description = "Asynchronously consolidate and introspect Rust crate interfaces, gathering typical items within a unified system for enhanced analysis and modification."
edition = "2024"
keywords = [
    "Rust",
    "AST",
    "consolidation",
    "async",
    "code-introspection",
]
license = "MIT OR Apache-2.0"
name = "workspacer-consolidate"
repository = "https://github.com/klebs6/klebs-general"
version = "0.5.2"
