[dependencies]
structopt.workspace      = true
derive_builder.workspace = true
serde.workspace          = true
serde_derive.workspace   = true
serde_json.workspace     = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.0"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-interface]
path = "../workspacer-interface"
version = "0.5.0"
[dependencies.workspacer-syntax]
path = "../workspacer-syntax"
version = "0.5.0"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "A utility crate for consolidating a crate's public interface into a single, unified structure."
edition = "2024"
license = "MIT OR Apache-2.0"
name = "workspacer-consolidate"
repository = "https://github.com/klebs6/klebs-general"
version = "0.5.0"
[[bin]]
name = "workspacer-show-consolidated-crate-interface"
path = "src/bin/show_consolidated_crate_interface.rs"
