// ---------------- [ File: hydro2-async-scheduler/src/lib.rs ]
#[macro_use] mod imports; use imports::*;

x!{aggregator_thread_behavior}
x!{check_all_nodes_done}
x!{async_scheduler_config}
x!{async_scheduler}
x!{batching_strategy}
x!{block_on_build_in_degrees}
x!{block_on_dispatch}
x!{block_on_init_zero_degrees}
x!{build_and_send_task_result}
x!{build_in_degrees}
x!{build_worker_pool_in_scope}
x!{checkpoint_callback}
x!{compute_freed_children}
x!{create_worker_channels}
x!{current_memory_usage_in_bytes}
x!{dispatch_scheduling}
x!{drain_all_worker_results}
x!{drain_channel}
x!{drain_leftover_results}
x!{execute_network_main_thread}
x!{execute_network}
x!{execute_node}
x!{fetch_next_task}
x!{force_close_for_single_node}
x!{gather_node_count_and_edges}
x!{handle_freed_children}
x!{handle_new_ready_node}
x!{initialize_zero_degree_nodes}
x!{mock_failing_operator_task}
x!{mock_minimal_task_item_with_permit}
x!{mock_permit}
x!{mock_task_with_checkpoint}
x!{mock_worker_pool}
x!{poll_worker_results}
x!{process_immediate_freed_child_received}
x!{process_immediate_ready_node_received}
x!{process_immediate}
x!{process_task}
x!{process_waves}
x!{read_next_wave}
x!{reenqueue_freed_child}
x!{release_concurrency}
x!{run_worker_pool_in_scope}
x!{spawn_aggregator_thread_and_workers}
x!{spawn_aggregator_thread}
x!{spawn_worker_thread}
x!{streaming_output}
x!{submit_chunk_to_worker_pool}
x!{task_item}
x!{task_result}
x!{validate_network}
x!{wait_until_all_tasks_in_chunk_are_done}
x!{worker_main}
x!{worker_pool}
x!{shared_completed_nodes}
x!{in_flight_counter}
