[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.1"

[dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.2.1"

[package]
authors = ["klebs tpk3.mx@gmail.com"]
description = "Utilities for extracting JSON and writing it to files with error handling."
edition = "2024"
license = "MIT"
name = "batch-mode-json"
repository = "https://github.com/klebs6/klebs-general"
version = "0.2.1"
