[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.0"
[package]
edition     = "2024"
name        = "batch-mode-json"
version     = "0.2.0"
description = "Utilities for extracting JSON and writing it to files with error handling."
authors     = ["klebs tpk3.mx@gmail.com"]
license     = "MIT"
repository  = "https://github.com/klebs6/klebs-general"
