[package]
edition = "2021"
name = "traced-test"
version = "0.5.0"
description = "this crate lets us use #[traced_test] to automatically configure sane default tracing for a rust test"
license = "MIT"
authors = [ "klebs tpk3.mx@gmail.com" ]
categories = ["development-tools"]
keywords = ["macros", "testing"]
repository = "https://github.com/klebs6/klebs-general"

[dependencies]
syn = "2.0.52"
quote = "1.0"
proc-macro2 = "1.0"
export-magic = "0.3.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "std", "env-filter"] }

[lib]
proc-macro = true

[dev-dependencies]
tracing-setup = "*"
traced-test = "*"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
