[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.batch-mode-batch-client]
path = "../batch-mode-batch-client"
[dependencies.batch-mode-batch-executor]
path = "../batch-mode-batch-executor"
[dependencies.batch-mode-batch-metadata]
path = "../batch-mode-batch-metadata"
[dependencies.batch-mode-batch-reconciliation]
path = "../batch-mode-batch-reconciliation"
[dependencies.batch-mode-batch-scribe]
path = "../batch-mode-batch-scribe"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
[package]
edition = "2024"
name = "batch-mode-batch-error"
version = "0.1.0"
