[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
derive_builder = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
syn = "2.0"
[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.traced-test]
version = "*"
[dependencies.tracing]
version = "*"
[dependencies.tracing-setup]
version = "*"
[dependencies.tracing-subscriber]
features = [ "env-filter", "json" ]
version = "*"
[dev-dependencies]
trybuild = "*"
[dev-dependencies.ai-json-template]
path = "../ai-json-template"
[lib]
proc-macro = true
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
categories = [ "development-tools", "code-generation" ]
description = "A proc-macro crate for deriving AI-oriented JSON templates from Rust structs, capturing doc comments as instructions."
edition = "2024"
keywords = [ "AI", "json-schema", "template", "doc-comments" ]
license = "MIT"
name = "ai-json-template-derive"
readme = "README.md"
repository = "https://github.com/klebs6/klebs-general"
version = "0.1.0"
[profile.test]
strip = "none"
