[dependencies]
pretty_assertions.workspace  = true
derive_builder.workspace     = true
getset.workspace             = true
export-magic.workspace       = true
proc-macro2.workspace        = true
quote.workspace              = true
serde.workspace              = true
serde_derive.workspace       = true
serde_json.workspace         = true
syn.workspace                = true
traced-test.workspace        = true
tracing.workspace            = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true

[dev-dependencies]
trybuild.workspace           = true

[dev-dependencies.ai-json-template]
path = "../ai-json-template"
[dev-dependencies.save-load-derive]
path = "../save-load-derive"
version = "0.1.0"
[dev-dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.2.0"
[lib]
proc-macro = true
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
categories = [ "development-tools", "code-generation" ]
description = "A proc-macro crate for deriving AI-oriented JSON templates from Rust structs, capturing doc comments as instructions."
edition = "2024"
keywords = [ "AI", "json-schema", "template", "doc-comments" ]
license = "MIT"
name = "ai-json-template-derive"
readme = "README.md"
repository = "https://github.com/klebs6/klebs-general"
version = "0.1.0"
[profile.test]
strip = "none"
