[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-register-internal-crate-in-prefix-group"
version = "0.1.0"
description = "A Rust crate to register new internal crates in a prefix group, automating dependency and module adjustments within workspace structures."
keywords = ["crates", "workspace", "dependency", "cargo", "automation"]
categories = ["development-tools", "config", "concurrency", "asynchronous", "parsing"]
