[package]
name = "world-region-repl"
version = "0.1.0"
edition = "2024"

license = "MIT"
description = "A repl for the world-region-db system"

[dependencies]
world-region-db                  = { version = "0.2.0", path     = "../world-region-db" }
strum                            = "0.27.0"
export-magic                     = "0.3.6"
world-region                     = { version = "0.6.0", path = "../world-region" }
fuzzy-matcher                    = "0.3.7"
crossterm                        = "0.28.1"
rustyline                        = "15.0.0"
traced-test                      = "1.0.4"
tracing                          = "0.1.41"
tracing-setup                    = "1.0.4"
tracing-subscriber               = "0.3"
tokio                            = { version = "1", features = ["full"] }
structopt                        = "0.3"
tempfile                         = "3"
serde                            = { version = "1", features = ["derive"] }
serde_cbor                       = "0.11"
serial_test                      = "3.2.0"
getset                           = "0.1.5"
derive_builder                   = "0.20.2"
usa                              = "0.8.0"
country                          = "0.5.0"
postal-code                      = "0.2.0"
abbreviation-trait               = "0.3.0"
error-tree                       = "0.6.0"
file-downloader                  = "0.2.0"
