[package]
name = "workspacer-3p"
version = "0.2.0"
edition = "2024"
authors = ["klebs tpk3.mx@gmail.com"]
description = "Workspacer is a Rust library for managing and validating workspaces and crates, with support for test coverage, circular dependency detection, and publishing readiness. This crate encapsulates its third party deps."
homepage   = "https://github.com/klebs6/klebs-general"
repository = "https://github.com/klebs6/klebs-general"
documentation = "https://docs.rs/workspacer"
readme = "README.md"
license = "MIT"
keywords = ["workspace", "crate", "validation", "coverage", "dependency"]
categories = ["development-tools"]

[dependencies]
export-magic            = "0.3.6"
error-tree              = "0.3.7"
traced-test             = "1.0.2"
tracing-setup           = "1.0.2"
serde                   = "1.0.210"
mockall                 = "0.11.4"
async-channel           = "2.3.1"
serde_json              = "1.0.128"
regex                   = "1.11.0"
notify                  = "6.1.1"
semver                  = "1.0.23"
toml                    = "0.8.19"
petgraph                = "0.6.5"
cargo_metadata          = "0.18.1"
tokio                   = {version  = "1.40.0", features      = ["full"] }
toml_edit               = { version = "0.22.24", features           = ["parse", "display"] }
cargo-lock              = "10.1.0"
getset                  = "0.1.4"
tempfile                = "3.17.0"
derive_builder          = "0.20.2"
tokio-stream            = "0.1.16"
tokio-util              = "0.7.12"
futures                 = "0.3.30"
async-trait             = "0.1.83"
tracing                 = "0.1.40"
uuid                    = {version  = "1.10.0", features      = ["v4"] }
tracing-subscriber      = { version = "0.3", default-features = false, features        = ["fmt", "std", "env-filter"] }
disable_macro           = "0.3.6"
ra_ap_syntax            = "0.0.237"
scan-crate-for-typedefs = "0.8.1"
async-try-from          = "0.1.0"

[dev-dependencies]
indoc      = "2.0.5"
mockall    = "0.11.4"
quickcheck = "1.0"

[build-dependencies]
scan-crate-for-typedefs = "0.8.1"
