[dependencies.hydro2-3p]
path = "../hydro2-3p"
version = "0.1.0"
[dependencies.hydro2-basic-operators]
path = "../hydro2-basic-operators"
version = "0.1.0"
[dependencies.hydro2-network-wire-derive]
path = "../hydro2-network-wire-derive"
version = "0.1.0"
[dependencies.hydro2-operator]
path = "../hydro2-operator"
version = "0.1.0"

[dependencies]
async-trait = "0.1.86"
derive_builder = "0.20.2"
traced-test = "1.0.2"
tracing = "0.1.41"
tracing-setup = "1.0.2"
tracing-subscriber = { version = "0.3.19", features = [ "env-filter", "json" ] }

[dev-dependencies]
trybuild = "1.0.103"
tokio = { version = "1.43.0", features = [ "full" ] }

[dev-dependencies.hydro2-operator-derive]
path = "../hydro2-operator-derive"
version = "0.1.0"

[package]
edition = "2024"
name = "hydro2-network"
version = "0.1.0"
