[dependencies.hydro2-3p]
path = "../hydro2-3p"
version = "0.1.0"
[dependencies.hydro2-basic-operators]
path = "../hydro2-basic-operators"
version = "0.1.0"
[dependencies.hydro2-network-wire-derive]
path = "../hydro2-network-wire-derive"
version = "0.1.0"
[dependencies.hydro2-operator]
path = "../hydro2-operator"
version = "0.1.0"

[dependencies]
async-trait.workspace        = true
derive_builder.workspace     = true
traced-test.workspace        = true
tracing.workspace            = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true

[dev-dependencies]
trybuild.workspace = true
tokio.workspace    = true

[dev-dependencies.hydro2-operator-derive]
path = "../hydro2-operator-derive"
version = "0.1.0"

[package]
edition     = "2024"
name        = "hydro2-network"
version     = "0.1.0"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "Core data structures and DAG logic for building operator-based networks in the hydro2 ecosystem."
readme      = "README.md"
license-file = "OGPv1"
