[package]
name        = "generate-report"
version     = "0.1.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A minimal crate providing a trait for generating reports."
license     = "MIT OR Apache-2.0"
