// ---------------- [ File: src/lib.rs ]
// ---------------- [ File: src/lib.rs ]
#![feature(more_qualified_paths)]
#![feature(type_alias_impl_trait)]
#![allow(unused_imports)]
#![allow(unreachable_code)]
#![allow(unused_variables)]

#[macro_use] mod imports; use imports::*;

pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/mod.rs"));
}

x!{address_record_from_element_and_country}
x!{address_record}
x!{addresses_from_pbf_file_with_house_numbers}
x!{attempt_storing_house_number_aggregator_in_db}
x!{build_all_region_data}
x!{build_city_search_prefix}
x!{build_world_address_if_possible}
x!{build_world_address}
x!{capture_stdout}
x!{chain_addresses_across_files}
x!{city_names_for_postal_code_in_region}
x!{city_name}
x!{cli}
x!{cli_hooks}
x!{collect_address_and_housenumber_data}
x!{collect_tags}
x!{compressed_list}
x!{create_address_stream_channel}
x!{create_data_access}
x!{create_small_osm_pbf_file}
x!{create_tiny_osm_pbf_with_housenumber}
x!{create_tiny_osm_pbf}
x!{data_access}
x!{db_decoder}
x!{dmv}
x!{download_and_parse_all_regions}
x!{dump}
x!{errors}
x!{expected_filename_for_region}
x!{extract_city_from_key}
x!{extract_house_number_range_from_element}
x!{extract_house_number_range_from_tags}
x!{filenames_match}
x!{filenames}
x!{finalize_address_validation}
x!{find_region_for_file}
x!{gather_all_zips_in_region}
x!{gather_city_key_value_pairs}
x!{gather_pbf_files}
x!{get_cbor_set_typed}
x!{get_city_set_for_key}
x!{get_element_id}
x!{get_postal_code_set_for_key}
x!{get_prefix_iterator}
x!{get_street_set_for_key}
x!{handle_pbf_house_number_extractor_in_thread}
x!{house_number_in_any_range}
x!{house_number_parsing_and_storage}
x!{house_number_ranges}
x!{indexing}
x!{infer_country_from_region}
x!{integrate_house_number_subranges_for_street}
x!{keys}
x!{list_all_addresses_in_pbf_dir}
x!{load_all_cities_for_region}
x!{load_all_streets_for_region}
x!{load_done_regions}
x!{load_existing_house_number_ranges}
x!{load_existing_street_ranges}
x!{load_house_number_ranges}
x!{merge_house_number_range}
x!{merge_new_subranges}
x!{meta_key}
x!{mock}
x!{normalize}
x!{obtain_pbf_file_for_region}
x!{open_database_at_path}
x!{open_osm_pbf_reader}
x!{open_pbf_reader_or_report_error}
x!{parse_address_record_if_any}
x!{parse_city_names}
x!{parse_housenumber_value}
x!{parse_integer}
x!{parse_osm_pbf_and_build_house_number_ranges}
x!{postal_codes_for_city_in_region}
x!{prefix_transform}
x!{prepare_osm_header_block}
x!{prepare_single_node_primitive_block}
x!{process_and_validate_addresses}
x!{process_single_osm_element}
x!{putget}
x!{region_data}
x!{region_done_traits}
x!{regional_records}
x!{regions}
x!{remote_data}
x!{retrieve_housenumber_value}
x!{serialize_primitive_block}
x!{seriallize_osm_header_block}
x!{stdout_backup}
x!{storage}
x!{store_house_number_ranges}
x!{store_merged_house_number_ranges}
x!{street_exists_globally}
x!{street_exists_in_city_in_region}
x!{street_exists_in_postal_code_in_region}
x!{street_names_for_city_in_region}
x!{street_names_for_postal_code_in_region}
x!{street_name}
x!{strip_leading_dot_slash}
x!{traits}
x!{try_assemble_address_record}
x!{try_build_address_record_from_tags}
x!{try_construct_city_name}
x!{try_construct_postal_code}
x!{try_construct_street_name}
x!{try_decode_postal_codes}
x!{try_extract_address_tags}
x!{try_resolve_country}
x!{unify_new_and_existing_ranges}
x!{update_aggregator_with_housenumber}
x!{update_street_house_numbers}
x!{validate_address}
x!{validate_all_addresses}
x!{validate_city_for_postal_code}
x!{validate_not_dir}
x!{validate_pbf_filename}
x!{validate_street_for_city}
x!{validate_street_for_postal_code}
x!{world_address}
x!{write_be_u32}
x!{write_cities_to_region_and_postal_code}
x!{write_cities_to_region_and_street}
x!{write_house_number_ranges_into_storage}
x!{write_indices}
x!{write_osm_pbf_file}
x!{write_postal_codes_to_region_and_city}
x!{write_postal_codes_to_region_and_street}
x!{write_streets_to_region_and_city}
x!{write_streets_to_region_and_postal_code}
x!{house_number_aggregator}
x!{pbf_creation}
x!{get_iterator}
