[dependencies]
derive_builder.workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-format-imports"
version = "0.1.0"
description = "A Rust crate for parsing, sorting, and formatting import statements across crates and workspaces. Uses RA-AP-syntax to reorganize 'use' statements by prefix, sort them alphabetically, and preserve comments."
keywords = ["rust-imports", "syntax-analysis", "code-formatting", "async-processing", "workspace-management"]
categories = ["development-tools", "parsing", "syntax", "code-generation", "text-processing"]
