[dependencies]
derive_builder.workspace = true
export-magic.workspace   = true
getset.workspace         = true
proc-macro2.workspace    = true
quote.workspace          = true
unsafe-erased.workspace  = true
syn.workspace            = true
tracing.workspace            = true

[dependencies.hydro2-3p]
path = "../hydro2-3p"
version = "0.1.0"

[dev-dependencies]
async-trait.workspace        = true
named-item.workspace         = true
named-item-derive.workspace  = true
trybuild.workspace           = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true
tokio.workspace              = true

[dev-dependencies.hydro2-operator]
path = "../hydro2-operator"
version = "0.1.0"

[features]
default = [  ]

[lib]
proc-macro = true

[package]
edition    = "2024"
name       = "hydro2-operator-derive"
version    = "0.1.0"
authors    = ["klebs tpk3.mx@gmail.com"]
repository = "https://github.com/klebs6/klebs-general"
readme     = "README.md"
description = "Procedural macro that derives implementations of hydro2-operator's OperatorInterface trait, including port enumeration and bridging code for up to four inputs/outputs."
license-file = "OGPv1"
