[dependencies]
derive_builder = "*"
export-magic = "*"
getset = "*"
proc-macro2 = "1.0"
quote = "1.0"
unsafe-erased = "*"
[dependencies.hydro2-3p]
path = "../hydro2-3p"
[dependencies.syn]
features = [ "derive", "parsing", "extra-traits" ]
version = "2.0"
[dev-dependencies]
async-trait = "*"
named-item = "0.6.0"
named-item-derive = "0.2.0"
trybuild = "*"
[dev-dependencies.hydro2-operator]
path = "../hydro2-operator"
version = "*"
[dev-dependencies.tokio]
features = [ "full" ]
version = "*"
[features]
default = [  ]
[lib]
proc-macro = true
[package]
edition = "2024"
name = "hydro2-operator-derive"
version = "0.1.0"
