[dependencies]
derive_builder = "0.20.2"
export-magic = "0.3.6"
getset = "0.1.4"
proc-macro2 = "1.0"
quote = "1.0"
unsafe-erased = "0.1.0"
[dependencies.hydro2-3p]
path = "../hydro2-3p"
version = "0.1.0"
[dependencies.syn]
features = [ "derive", "parsing", "extra-traits" ]
version = "2.0"
[dev-dependencies]
async-trait = "0.1.86"
named-item = "0.6.0"
named-item-derive = "0.2.0"
trybuild = "1.0.103"
tracing                   = { version = "0.1.40", features = ["log"] }
tracing-setup             = "1.0.2"
tracing-subscriber        = { version = "0.3", default-features = false, features = ["fmt", "std", "env-filter"] }
tokio = { version = "1.43.0", features = [ "full" ] }

[dev-dependencies.hydro2-operator]
path = "../hydro2-operator"
version = "0.1.0"

[features]
default = [  ]

[lib]
proc-macro = true

[package]
edition = "2024"
name = "hydro2-operator-derive"
version = "0.1.0"
