[package]
name          = "named-item-derive"
version       = "0.1.0"
edition       = "2024"
description   = "A single procedural macro that implements NamedItem and optionally enables name history or aliases based on struct fields."
license       = "MIT"
repository    = "https://github.com/klebs6/klebs-general"
homepage      = "https://github.com/klebs6/klebs-general"
documentation = "https://docs.rs/named-item-derive"
readme        = "README.md"

[lib]
proc-macro = true

[dependencies]
syn         = "2"
quote       = "1"
proc-macro2 = "1"
#named-item  = { version = "*", path = "../named-item" }
named-item  = "*"
[dev-dependencies]
trybuild = "1.0.101"
