[package]
name = "plural-trait"
version = "0.1.0"
edition = "2021"

description = "This crate contains the trait we use with the plural-derive proc macro"
authors = [ "klebs tpk3.mx@gmail.com" ]
license = "MIT"
keywords = ["macros", "shorthand", "plural" ]
repository = "https://github.com/klebs6/klebs-general"
categories = ["development-tools"]

[dependencies]
