[package]
name = "postal-code"
version = "0.1.0"
edition = "2024"

description = "A robust, production-grade Rust library for validating international postal codes."
authors = [ "klebs tpk3.mx@gmail.com" ]
license = "MIT"
repository = "https://github.com/klebs6/klebs-general"
documentation = "https://docs.rs/postal-code"
readme = "README.md"
keywords = ["postage", "zipcode", "validation", "international", "country"]
categories = ["internationalization"]

[dependencies]
derive_builder = "0.11"
getset         = "0.1"
delegate       = "0.9"
serde          = { version = "1", features = ["derive"] }
serde_json     = "1"
regex          = "1"
once_cell      = "1"
lazy_static    = "1"
country        = "0.3.0"
export-magic   = "0.3.6"
paste          = "1.0.15"

[dev-dependencies]
rand = "0.8.5"
