[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.1"

[dependencies.batch-mode-batch-index]
path = "../batch-mode-batch-index"
version = "0.2.1"

[dependencies.camel-case-token-with-comment]
path = "../camel-case-token-with-comment"
version = "0.2.1"

[dependencies.derive_builder]
workspace = true

[dependencies.getset]
workspace = true

[package]
authors = ["klebs tpk3.mx@gmail.com"]
description = "Defines traits for interacting with batch workspaces, including file paths and directories."
edition = "2024"
license = "MIT"
name = "batch-mode-batch-workspace-interface"
repository = "https://github.com/klebs6/klebs-general"
version = "0.2.1"
