[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.1.0"
[dependencies.batch-mode-batch-index]
path = "../batch-mode-batch-index"
version = "0.1.0"
[dependencies.batch-mode-batch-schema]
path = "../batch-mode-batch-schema"
version = "0.1.0"
[dependencies.batch-mode-json]
path = "../batch-mode-json"
version = "0.1.0"
[dependencies.batch-mode-batch-workspace-interface]
path = "../batch-mode-batch-workspace-interface"
version = "0.1.0"
[package]
edition = "2024"
name = "batch-mode-batch-triple"
version = "0.1.0"
description = "Manages batch file triples (input, output, error, metadata) in batch processing systems, including file validation, error handling, and file movement."
authors = ["klebs tpk3.mx@gmail.com"]
license = "MIT"
repository = "https://github.com/klebs6/klebs-general"
