[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-interface"
version = "0.5.0"