[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-interface"
version = "0.5.0"
description = "A comprehensive API for workspace management, offering customizable layouts and efficient task handling."
keywords = ["workspace", "task-management", "layout", "API", "window-positioning"]
categories = ["development-tools", "gui", "window-management", "api-bindings", "data-structures"]
