[dependencies]
workspacer-3p              = { version = "0.1.0", path = "../workspacer-3p" }
get-file-size              = { version = "0.1.0", path = "../get-file-size" }
lightweight-command-runner = { version = "0.1.0", path = "../lightweight-command-runner" }

[package]
name        = "workspacer-interface"
version     = "0.1.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "Core trait definitions and error types for the Workspacer ecosystem, providing unified interfaces for workspace and crate management."
license     = "MIT OR Apache-2.0"
