[package]
name        = "hydro2-3p"
version     = "0.1.0"
edition     = "2024"
description = "This crate encapsulates the third party (3p) dependencies for the hydro2 system"
repository  = "https://github.com/klebs6/klebs-general"
readme      = "README.md"
license-file = "OGPv1"

[dependencies]
async-trait.workspace        = true
derive_builder.workspace     = true
disable_macro.workspace      = true
error-tree.workspace         = true
export-magic.workspace       = true
futures.workspace            = true
getset.workspace             = true
named-item.workspace         = true
named-item-derive.workspace  = true
num-traits.workspace         = true
serde.workspace              = true
serde_json.workspace         = true
tokio.workspace              = true
traced-test.workspace        = true
tracing.workspace            = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true
lazy_static.workspace        = true
pbx.workspace                = true
rand.workspace               = true

[build-dependencies]
scan-crate-for-typedefs.workspace = true
