[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml]
path = "../workspacer-toml"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-name-all-files"
version = "0.1.0"
description = "Recursively scans directories for Rust source files, manages file markers, and integrates with workspace environments using asynchronous Rust."
keywords = ["workspace", "file-management", "asynchronous", "rust", "files"]
categories = ["development-tools", "asynchronous", "filesystem", "rust-patterns", "parsing"]
[[bin]]
name = "workspacer-name-all-files"
path = "src/bin/name_all_files.rs"
