[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-tree"
publish = [ "mock" ]
version = "0.1.0"
description = "A Rust crate to asynchronously build and render workspace dependency trees for Rust projects. It provides tools for managing and visualizing dependencies using graph-based approaches."
keywords = ["rust", "dependency", "workspace", "async", "tree"]
categories = ["development-tools", "algorithms", "asynchronous", "network-programming", "rendering"]
