[dependencies]
workspacer-3p        = { version = "0.2.0", path = "../workspacer-3p" }
workspacer-crate     = { version = "0.2.0", path = "../workspacer-crate" }
workspacer-interface = { version = "0.2.0", path = "../workspacer-interface" }
get-file-size        = { version = "0.1.0", path = "../get-file-size" }

[package]
name        = "workspacer-mock"
version     = "0.2.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A utility crate for creating mock workspaces with configurable member crates for testing and development, as part of the Workspacer ecosystem."
license     = "MIT OR Apache-2.0"
