[dependencies.get-file-size]
path = "../get-file-size"
version = "0.1.0"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.0"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-interface]
path = "../workspacer-interface"
version = "0.5.0"
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "A utility crate for creating mock workspaces with configurable member crates for testing and development, as part of the Workspacer ecosystem."
edition = "2024"
license = "MIT OR Apache-2.0"
name = "workspacer-mock"
repository = "https://github.com/klebs6/klebs-general"
version = "0.5.0"
