[dependencies]
workspacer-3p        = "0.1.0"
workspacer-crate     = "0.1.0"
workspacer-interface = "0.1.0"
get-file-size        = "0.1.0"

[package]
name        = "workspacer-mock"
version     = "0.1.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A utility crate for creating mock workspaces with configurable member crates for testing and development, as part of the Workspacer ecosystem."
license     = "MIT OR Apache-2.0"
