[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[package]
categories = [
    "development-tools",
    "testing",
    "workspace",
    "trace",
    "debug",
]
description = "Trace and validate upgrade processes in workspace-style Rust projects, providing detailed execution profiles for improved refactoring workflows."
edition = "2024"
keywords = [
    "workspace",
    "tracing",
    "upgrade",
    "testing",
    "utility",
]
name = "workspacer-upgrade-test-suite-tracing"
version = "0.1.1"
license = "MIT"
