[package]
name        = "batch-mode-3p"
version     = "0.2.0"
edition     = "2024"
description = "This crate contains the third party (3p) interface for the `batch-mode` crate ecosystem"
authors     = ["klebs tpk3.mx@gmail.com"]
license     = "MIT"
repository  = "https://github.com/klebs6/klebs-general"

[dependencies]
pretty_assertions.workspace        = true
async-openai.workspace             = true
export-magic.workspace             = true
uuid.workspace                     = true
regex.workspace                    = true
bytes.workspace                    = true
tempfile.workspace                 = true
serde.workspace                    = true
serde_json.workspace               = true
tokio.workspace                    = true
futures.workspace                  = true
error-tree.workspace               = true
disable_macro.workspace            = true
async-trait.workspace              = true
indoc.workspace                    = true
Inflector.workspace                = true
tracing.workspace                  = true
tracing-subscriber.workspace       = true
delegate.workspace                 = true
traced-test.workspace              = true
tracing-setup.workspace            = true
json5.workspace                    = true
crossbeam.workspace                = true
float-ord.workspace                = true
num-traits.workspace               = true
pbx.workspace                      = true
json-repair.workspace              = true
once_cell.workspace                = true
strsim.workspace                   = true
rand.workspace                     = true
rand-construct.workspace           = true
structopt.workspace                = true
ai-descriptor.workspace            = true
structured-language-form.workspace = true
named-item.workspace               = true
named-item-derive.workspace        = true
getset.workspace                   = true
derive_builder.workspace           = true
strum.workspace                    = true
strum_macros.workspace             = true
lazy_static.workspace              = true

[build-dependencies]
scan-crate-for-typedefs.workspace  = true
