[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-metadata]
path = "../workspacer-metadata"
[dependencies.workspacer-mock]
path = "../workspacer-mock"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-detect-circular-deps"
version = "0.1.0"