[workspace]
resolver = "3"
members = [ 
    "workspacer-3p", 
    "workspacer-toml", 
    "workspacer-crate", 
    "workspacer-mock", 
    "command-runner", 
    "generate-report", 
    "workspacer-syntax", 
    "workspacer-consolidate", 
    "workspacer-interface", 
    "get-file-size", 
    "workspacer" 
]
