[profile.test]
strip = "none"
[workspace]
members = [ "lightweight-command-runner", "generate-report-trait", "get-file-size", "workspacer", "workspacer-3p", "workspacer-consolidate", "workspacer-crate", "workspacer-interface", "workspacer-mock", "workspacer-syntax", "workspacer-toml", "workspacer-watch-and-reload", "workspacer-analysis", "workspacer-test-coverage", "workspacer-rebuild-or-test", "workspacer-publish", "workspacer-pin", "workspacer-name-all-files", "workspacer-metadata", "workspacer-linting", "workspacer-docs", "workspacer-git", "workspacer-cleanup", "workspacer-detect-circular-deps", "workspacer-workspace", "workspacer-errors", "workspacer-crate-interface", "workspacer-workspace-interface", "workspacer-toml-interface", "workspacer-readme-writer", "workspacer-register", "workspacer-format-imports", "workspacer-add-new-crate-to-workspace", "workspacer-lock", "workspacer-scan-for-prefix-groups", "workspacer-add-internal-dep", "workspacer-register-internal-crate-in-prefix-group", "workspacer-bump", "workspacer-document", "workspacer-git-commit", "workspacer-ensure-git-clean", "workspacer-info", "workspacer-organize", "workspacer-register-crate-files", "workspacer-show-dependency-tree", "workspacer-upgrade-function-tracing", "workspacer-upgrade-test", "workspacer-upgrade-test-suites", "workspacer-upgrade-test-suite-tracing", "workspacer-upgrade-test-tracing", "workspacer-upgrade-tracing", "workspacer-validate", "workspacer-show", "workspacer-check-publish-ready", "workspacer-check-crates-io", "workspacer-check-private", "workspacer-config", "workspacer-toml-mock", "workspacer-crate-mock", "workspacer-workspace-mock", "workspacer-cratesio-mock", "workspacer-cli", "workspacer-export", "workspacer-tree", "sync-run-async", "workspacer-prune-bad-category-slugs" ]
resolver = "3"
[workspace.dependencies]
async-channel = "2.3.1"
async-trait = "0.1.83"
async-try-from = "0.2.0"
cargo-lock = "10.1.0"
cargo_metadata = "0.18.1"
colored = "2.2.0"
derive_builder = "0.20.2"
dirs = "6.0.0"
disable_macro = "0.3.6"
error-tree = "0.6.0"
export-magic = "0.3.6"
futures = "0.3.30"
getset = "0.1.4"
indoc = "2.0.6"
lazy_static = "1.5.0"
mockall = "0.11.4"
named-item = "0.6.0"
named-item-derive = "0.2.0"
notify = "6.1.1"
pathdiff = "0.2.3"
petgraph = "0.6.5"
portpicker = "0.1.1"
quickcheck = "1.0"
ra_ap_syntax = "0.0.237"
regex = "1.11.0"
reqwest = "0.12.12"
scan-crate-for-typedefs = "0.8.1"
semver = "1.0.23"
serde = "1.0.217"
serde_derive = "1.0.219"
serde_json = "1.0.138"
structopt = "0.3.26"
tempfile = "3.17.0"
tokio-stream = "0.1.16"
tokio-util = "0.7.12"
toml = "0.8.19"
tracing = "0.1.40"
which = "7.0.2"
[workspace.dependencies.batch-mode]
path = "../batch-mode/batch-mode"
version = "0.2.1"
[workspace.dependencies.rocket]
features = [ "json" ]
version = "0.5.1"
[workspace.dependencies.tokio]
features = [ "full" ]
version = "1.40.0"
[workspace.dependencies.toml_edit]
features = [ "parse", "display" ]
version = "0.22.24"
[workspace.dependencies.traced-test]
path = "../traced-test"
version = "1.0.3"
[workspace.dependencies.tracing-setup]
path = "../tracing-setup"
version = "1.0.3"
[workspace.dependencies.tracing-subscriber]
default-features = false
features = [ "fmt", "std", "env-filter" ]
version = "0.3"
[workspace.dependencies.uuid]
features = [ "v4" ]
version = "1.10.0"