[dependencies.tracing]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.2"

[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.2"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.2"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.2"

[dependencies.workspacer-toml]
path = "../workspacer-toml"
version = "0.5.2"

[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
version = "0.1.3"

[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.2"

[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
version = "0.1.3"

[package]
description = "This workspacer crate lets us prune bad category slugs from our toml files before publishing"
edition = "2024"
license = "MIT"
name = "workspacer-prune-bad-category-slugs"
version = "0.1.1"
