[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-cleanup"
version = "0.1.0"
description = "A Rust crate for asynchronous cleanup of unnecessary files and directories in a workspace, maintaining development efficiency."
keywords = ["rust", "workspace", "cleanup", "async", "filesystem"]
categories = ["development-tools", "asynchronous", "filesystem", "utilities"]
