[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.1"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.1"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.1"

[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
version = "0.1.2"

[package]
categories = [
    "asynchronous",
    "concurrency",
    "development-tools",
    "parsing",
    "filesystem",
]
description = "A Rust crate for retrieving Cargo workspace metadata asynchronously, using Tokio for task management and async_trait for non-blocking trait-based operations."
edition = "2024"
keywords = [
    "async",
    "metadata",
    "cargo",
    "workspace",
    "tokio",
]
name = "workspacer-metadata"
version = "0.1.2"
license = "MIT"
