[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-metadata"
version = "0.1.0"
description = "A Rust crate for retrieving Cargo workspace metadata asynchronously, using Tokio for task management and async_trait for non-blocking trait-based operations."
keywords = ["async", "metadata", "cargo", "workspace", "tokio"]
categories = ["asynchronous", "concurrency", "development-tools", "parsing", "filesystem"]
