[dependencies.tracing]
workspace = true

[dependencies.derive_builder]
workspace = true

[dependencies.structopt]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-either]
path = "../workspacer-either"
version = "0.1.0"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[dependencies.workspacer-export]
path = "../workspacer-export"
version = "0.1.3"

[dependencies.workspacer-file-filter]
path = "../workspacer-file-filter"
version = "0.1.0"

[dependencies.workspacer-prune-bad-category-slugs]
path = "../workspacer-prune-bad-category-slugs"
version = "0.1.0"

[dependencies.workspacer-run]
path = "../workspacer-run"
version = "0.1.0"

[dependencies.workspacer-show]
path = "../workspacer-show"
version = "0.1.1"

[package]
categories = [
    "command-line-utilities",
    "development-tools",
    "parsing",
]
description = "A versatile command-line interface for Rust workspace management, providing comprehensive controls for crate analysis, import formatting, cleanup, dependency checks, and more."
edition = "2024"
keywords = [
    "workspace",
    "crate",
    "cli",
    "automation",
    "rust",
]
license = "MIT"
name = "workspacer-cli"
version = "0.1.1"
