[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.1.0"
[dependencies.batch-mode-batch-index]
path = "../batch-mode-batch-index"
version = "0.1.0"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
version = "0.1.0"
[dependencies.batch-mode-json]
path = "../batch-mode-json"
version = "0.1.0"
[dependencies.camel-case-token-with-comment]
path = "../camel-case-token-with-comment"
version = "0.1.0"
[dependencies.batch-mode-batch-workspace-interface]
path = "../batch-mode-batch-workspace-interface"
version = "0.1.0"
[dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.1.0"

[dependencies]
traced-test = "1.0.2"
tracing = "0.1.41"
tracing-setup = "1.0.2"
tracing-subscriber = { version = "0.3.19", features = [ "env-filter", "json"] }


[package]
edition = "2024"
name = "batch-mode-batch-workspace"
version = "0.1.0"
description = "Manages batch processing workspaces, handling tasks like locating batch files, validating files, and managing batch indices."
authors = ["klebs tpk3.mx@gmail.com"]
license = "MIT"
repository = "https://github.com/klebs6/klebs-general"
