[package]
name          = "lyrical-meter"
version       = "0.2.0"
edition       = "2021"
authors       = [ "klebs tpk3.mx@gmail.com" ]
description   = "A Rust crate for representing and working with various poetic meters."
license       = "MIT OR Apache-2.0"
repository    = "https://github.com/klebs6/klebs-general"
homepage      = "https://github.com/klebs6/klebs-general"
documentation = "https://docs.rs/lyrical-meter"
readme        = "README.md"
keywords      = ["poetry", "metrical", "verse", "literature", "text"]
categories    = ["text-processing", "data-structures"]

[dependencies]
export-magic = "0.3.6"
rand         = "0.8.5"
serde        = { version = "1.0", features = ["derive"] }
serde_json   = "1.0"
ai-descriptor = "0.8.0"
rand-construct = "0.10.0"
