[dependencies.agent-coordinate]
path = "../agent-coordinate"
[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.batch-mode-batch-client]
path = "../batch-mode-batch-client"
[dependencies.batch-mode-batch-error]
path = "../batch-mode-batch-error"
[dependencies.batch-mode-batch-executor]
path = "../batch-mode-batch-executor"
[dependencies.batch-mode-batch-index]
path = "../batch-mode-batch-index"
[dependencies.batch-mode-batch-metadata]
path = "../batch-mode-batch-metadata"
[dependencies.batch-mode-batch-reconciliation]
path = "../batch-mode-batch-reconciliation"
[dependencies.batch-mode-batch-scribe]
path = "../batch-mode-batch-scribe"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
[dependencies.batch-mode-batch-workflow]
path = "../batch-mode-batch-workflow"
[dependencies.batch-mode-batch-workspace]
path = "../batch-mode-batch-workspace"
[dependencies.batch-mode-batch-workspace-interface]
path = "../batch-mode-batch-workspace-interface"
[dependencies.batch-mode-process-response]
path = "../batch-mode-process-response"
[dependencies.camel-case-token-with-comment]
path = "../camel-case-token-with-comment"
[dependencies.language-model-batch-workflow-derive]
path = "../language-model-batch-workflow-derive"
[dependencies.language-model-type]
path = "../language-model-type"
[dependencies.save-load-traits]
path = "../save-load-traits"

[dependencies]
async-trait        = { version  = "0.1.86" }
tracing            = { version  = "0.1.41" }
tracing-setup      = { version  = "1.0.2" }
tracing-subscriber = { features = [ "env-filter", "json" ], version = "0.3.19" }

[package]
authors     = ["klebs tpk3.mx@gmail.com"]
categories  = ["text-processing", "api-bindings"]
description = "A crate for token expansion, leveraging batch workflows and language model APIs."
edition     = "2024"
keywords    = ["token", "expansion", "batch", "workflow", "language-model"]
license     = "MIT"
name        = "language-model-token-expander"
readme      = "README.md"
repository  = "https://github.com/klebs6/klebs-general"
version     = "0.1.0"
