[package]
authors       = [ "klebs <tpk3.mx@gmail.com>" ]
categories    = ["text-processing"]
description   = "A Rust library for representing personal names with optional titles, middle names/initials, and convenience macros."
documentation = "https://docs.rs/name-and-title"
edition       = "2024"
include       = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]
keywords      = ["name", "title", "builder", "serde"]
license       = "MIT"
name          = "name-and-title"
readme        = "README.md"
repository    = "https://github.com/klebs6/klebs-general"
version       = "0.1.0"

[dependencies]
serde_json = "1.0.133"
serde_derive = "1.0.216"
export-magic = "0.3.6"
derive_builder = "0.20.2"
getset = "0.1.3"

[dependencies.serde]
version = "1.0.216"
features = ["derive"]
