[dependencies]
derive_builder.workspace     = true
getset.workspace             = true
traced-test.workspace        = true
tracing.workspace            = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true

[dependencies.batch-mode-3p]
path = "../batch-mode-3p"

[package]
edition = "2024"
name = "agent-coordinate"
version = "0.1.0"
