[package]
edition = "2021"
name = "language-enum"
version = "0.1.0"
[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
export-magic = "0.3.6"
[dependencies.serde]
features = [ "derive" ]
version = "*"

