[package]
edition = "2021"
name = "language-enum"
version = "0.2.0"
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "A robust enum representing languages for global and regional applications."
license = "MIT OR Apache-2.0"
repository = "https://github.com/klebs6/klebs-general"
documentation = "https://docs.rs/language-enum"
keywords = ["languages", "enum", "internationalization", "i18n", "globalization"]
categories = ["internationalization", "data-structures"]

[dependencies]
serde = { optional = true, version = "1.0", features = ["derive"] }
serde_derive = { version = "1.0", optional = true }
serde_json = "1.0"
export-magic = "0.3.6"
rand-construct = "0.10.0"
ai-descriptor = "*"
rand = "0.8.5"

[features]
default = ["serde"] 
serde = ["dep:serde", "dep:serde_derive"]
