[dependencies]
export-magic.workspace = true
async-trait.workspace  = true
error-tree.workspace   = true
tokio.workspace        = true

[dev-dependencies]
tempfile.workspace = true

[package]
name        = "get-file-size"
version     = "0.1.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "An asynchronous utility crate for obtaining file size and counting lines in files."
license     = "MIT OR Apache-2.0"
