[dependencies]
export-magic = "0.3.6"
async-trait  = "0.1.86"
error-tree   = "0.3.7"
tokio        = {version = "1.40.0", features = ["full"] }

[package]
name        = "get-file-size"
version     = "0.1.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "An asynchronous utility crate for obtaining file size and counting lines in files."
license     = "MIT OR Apache-2.0"
