[dependencies]
derive_builder = "0.20.2"
[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.batch-mode-batch-reconciliation]
path = "../batch-mode-batch-reconciliation"
[dependencies.batch-mode-batch-scribe]
path = "../batch-mode-batch-scribe"
[dependencies.language-model-type]
path = "../language-model-type"

[dependencies]
traced-test = { version = "*" }
tracing = { version = "*" }
async-trait = { version = "*" }
tracing-setup = { version = "*" }
tracing-subscriber = { version = "*", features = [ "env-filter", "json" ] }

[package]
edition = "2024"
name = "batch-mode-batch-workflow"
version = "0.1.0"

[dependencies.batch-mode-batch-workspace]
path = "../batch-mode-batch-workspace"
[dependencies.batch-mode-batch-metadata]
path = "../batch-mode-batch-metadata"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
[dependencies.batch-mode-json]
path = "../batch-mode-json"
[dependencies.batch-mode-batch-client]
path = "../batch-mode-batch-client"
[dependencies.batch-mode-batch-executor]
path = "../batch-mode-batch-executor"
[dependencies.batch-mode-process-response]
path = "../batch-mode-process-response"
