[dependencies.batch-mode-3p]
path = "../batch-mode-3p"

[package]
authors     = ["klebs tpk3.mx@gmail.com"]
categories  = ["development-tools", "code-generation"]
description = "A procedural macro crate for deriving token expansion axes."
edition     = "2024"
keywords    = ["token", "proc-macro", "axis", "expansion"]
license     = "MIT"
name        = "batch-mode-token-expansion-axis-derive"
readme      = "README.md"
repository  = "https://github.com/klebs6/klebs-general"
version     = "0.1.0"

[dependencies]
syn         = { version = "2.0", features = ["derive", "parsing"] }
quote       = "1.0"
proc-macro2 = "1.0"

[dev-dependencies.batch-mode-token-expansion-axis]
path = "../batch-mode-token-expansion-axis"

[features]
default = []

[lib]
proc-macro = true
