[dev-dependencies.save-load-traits]
path = "../save-load-traits"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0.104"
tokio = { version = "1", features = ["macros"] }

[dependencies.traced-test]
version = "1.0.2"
[dependencies.tracing]
version = "0.1.41"
[dependencies.tracing-setup]
version = "1.0.2"
[dependencies.tracing-subscriber]
features = [ "env-filter", "json" ]
version = "0.3.19"

[dependencies]
proc-macro2    = "1.0"
pretty_assertions = "1.4.1"
quote          = "1.0"
derive_builder = "0.20.2"
serde          = "1.0"
serde_derive   = "1.0"
serde_json     = "1.0"
syn            = "2.0"
async-trait    = "0.1"
getset         = "0.1.5"
tempfile       = "3"

[package]
edition     = "2024"
name        = "save-load-derive"
version     = "0.1.0"
authors     = [ "klebs tpk3.mx@gmail.com" ]
categories  = [ "development-tools", "code-generation" ]
license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/klebs6/klebs-general"
description = "Provides the SaveLoad proc macro, for easy async saving to and from files for serde objects."
