[dev-dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.2.0"

[lib]
proc-macro = true

[dev-dependencies]
trybuild.workspace = true
tokio.workspace    = true

[dependencies]
async-trait.workspace        = true
derive_builder.workspace     = true
getset.workspace             = true
pretty_assertions.workspace  = true
proc-macro2.workspace        = true
quote.workspace              = true
serde.workspace              = true
serde_derive.workspace       = true
serde_json.workspace         = true
syn.workspace                = true
tempfile.workspace           = true
traced-test.workspace        = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true
tracing.workspace            = true

[package]
edition     = "2024"
name        = "save-load-derive"
version     = "0.1.0"
authors     = [ "klebs tpk3.mx@gmail.com" ]
categories  = [ "development-tools", "code-generation" ]
license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/klebs6/klebs-general"
description = "Provides the SaveLoad proc macro, for easy async saving to and from files for serde objects."
