[dependencies.agent-coordinate]
path = "../agent-coordinate"
[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.batch-mode-batch-scribe]
path = "../batch-mode-batch-scribe"
[dependencies.batch-mode-token-expansion-axis]
path = "../batch-mode-token-expansion-axis"
[dependencies.batch-mode-token-expansion-step]
path = "../batch-mode-token-expansion-step"
[dependencies.camel-case-token-with-comment]
path = "../camel-case-token-with-comment"
[dependencies.language-model-format-instructions]
path = "../language-model-format-instructions"
[dependencies.language-model-type]
path = "../language-model-type"
[dependencies.save-load-traits]
path = "../save-load-traits"

[package]
edition     = "2024"
name        = "batch-mode-token-expander"
version     = "0.1.0"
authors     = ["klebs tpk3.mx@gmail.com"]
categories  = ["text-processing", "api-bindings"]
description = "A crate for expanding tokens in a batch, suitable for orchestrating language model requests."
keywords    = ["token", "expansion", "batch", "language-model"]
license     = "MIT"
readme      = "README.md"
repository  = "https://github.com/klebs6/klebs-general"
