[dependencies.hydro2-async-scheduler]
path = "../hydro2-async-scheduler"
version = "0.1.0"
[dependencies.hydro2-basic-operators]
path = "../hydro2-basic-operators"
version = "0.1.0"
[dependencies.hydro2-network]
path = "../hydro2-network"
version = "0.1.0"
[dependencies.hydro2-network-performance]
path = "../hydro2-network-performance"
version = "0.1.0"
[dependencies.hydro2-network-wire-derive]
path = "../hydro2-network-wire-derive"
version = "0.1.0"
[dependencies.hydro2-operator]
path = "../hydro2-operator"
version = "0.1.0"
[dependencies.hydro2-operator-derive]
path = "../hydro2-operator-derive"
version = "0.1.0"

[package]
edition      = "2024"
name         = "hydro2"
version      = "0.1.0"
description  = "This crate encapsulates the `hydro2` system."
repository   = "https://github.com/klebs6/klebs-general"
readme       = "README.md"
license-file = "OGPv1"
