[package]
edition = "2024"
name    = "workspacer-crate-mock"
version = "0.1.0"
description = "Simulate Rust crate structures and behaviors without filesystem interference, via reproducible mock interfaces."
keywords = ["rust", "crate", "mocking", "simulation", "testing"]
categories = ["development-tools", "simulation", "filesystem", "testing", "mocking"]

[dependencies]
derive_builder.workspace = true
getset.workspace         = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml-mock]
path = "../workspacer-toml-mock"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[dependencies.workspacer-toml]
path = "../workspacer-toml"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
