[dependencies]
derive_builder = "*"
[dependencies.hydro2-3p]
path = "../hydro2-3p"
[dependencies.hydro2-basic-operators]
path = "../hydro2-basic-operators"
[dependencies.hydro2-network]
path = "../hydro2-network"
[dependencies.hydro2-network-performance]
path = "../hydro2-network-performance"
[dependencies.hydro2-operator]
path = "../hydro2-operator"
[dependencies.serde]
features = [ "derive" ]
version = "*"
[dependencies.serde_derive]
version = "*"
[dependencies.serde_json]
version = "*"
[dependencies.traced-test]
version = "*"
[dependencies.tracing]
version = "*"
[dependencies.tracing-setup]
version = "*"
[dependencies.tracing-subscriber]
features = [ "env-filter", "json" ]
version = "*"
[dev-dependencies.hydro2-mock]
path = "../hydro2-mock"
version = "*"
[package]
edition     = "2024"
name        = "hydro2-async-scheduler"
version     = "0.1.0"
license     = "MIT"
repository  = "https://github.com/klebs6/klebs-general"
description = "An asynchronous DAG-based scheduling framework for parallel operator execution."
readme      = "README.md"
