[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-git]
path = "../workspacer-git"
[dependencies.workspacer-lock]
path = "../workspacer-lock"
[dependencies.workspacer-toml]
path = "../workspacer-toml"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-pin"
version = "0.1.0"
description = "A Rust crate for pinning wildcard dependencies within workspaces using local versions or lockfile fallbacks, ensuring reliable and reproducible builds. Supports async operations and complex nested structures in `Cargo.toml`."
keywords = ["dependencies", "pinning", "workspace", "versioning", "rust"]
categories = ["development-tools", "dependencies"]
[[bin]]
name = "workspacer-pin-wildcard-deps"
path = "src/bin/pin_wildcard_deps.rs"
