[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"

[package]
categories = [
    "development-tools",
    "data-structures",
    "algorithms",
    "parsing",
    "network-programming",
]
description = "A Rust crate offering utilities for workspace information management and dynamic data retrieval in software projects."
edition = "2024"
keywords = [
    "workspace",
    "information",
    "data-retrieval",
    "analytics",
    "utilities",
]
name = "workspacer-info"
version = "0.1.1"
