[dependencies.workspacer-3p]
path = "../workspacer-3p"
[package]
edition = "2024"
name = "workspacer-info"
version = "0.1.0"
description = "A Rust crate offering utilities for workspace information management and dynamic data retrieval in software projects."
keywords = ["workspace", "information", "data-retrieval", "analytics", "utilities"]
categories = ["development-tools", "data-structures", "algorithms", "parsing", "network-programming"]
