[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.1"

[dependencies.derive_builder]
workspace = true

[dependencies.getset]
workspace = true

[dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.2.1"

[dependencies.serde]
workspace = true

[dependencies.serde_derive]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.traced-test]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tracing-setup]
workspace = true

[dependencies.tracing-subscriber]
workspace = true

[package]
authors = ["klebs tpk3.mx@gmail.com"]
description = "Provides utilities for managing, serializing, and persisting batch metadata, including input, output, and error file IDs, with support for JSON serialization and file persistence."
edition = "2024"
license = "MIT"
name = "batch-mode-batch-metadata"
repository = "https://github.com/klebs6/klebs-general"
version = "0.2.1"
