[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.0"
[dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.2.0"

[dependencies]
serde.workspace              = true
serde_derive.workspace       = true
derive_builder.workspace     = true
getset.workspace             = true
serde_json.workspace         = true
traced-test.workspace        = true
tracing.workspace            = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true

[package]
edition = "2024"
name = "batch-mode-batch-metadata"
version = "0.2.0"
description = "Provides utilities for managing, serializing, and persisting batch metadata, including input, output, and error file IDs, with support for JSON serialization and file persistence."
authors = ["klebs tpk3.mx@gmail.com"]
license = "MIT"
repository = "https://github.com/klebs6/klebs-general"
