#![allow(unused_imports)]
#![allow(unused_variables)]
#[macro_use] pub mod imports; use imports::*;

x!{analyze_workspace}
x!{async_traits}
x!{cargo_toml_handle}
x!{cargo_toml_interface}
x!{cleanup}
x!{command_runner}
x!{count_lines_in_file}
x!{crate_analysis}
x!{crate_handle}
x!{crate_handle_interface}
x!{dependency_tree}
x!{detect_circular_dependencies}
x!{errors}
x!{exit_status}
x!{generate_docs}
x!{get_file_size}
x!{lint_report}
x!{linting}
x!{metadata}
x!{mock}
x!{mock_crate_config}
x!{rebuild_or_test}
x!{report}
x!{test_coverage}
x!{test_coverage_command}
x!{test_coverage_report}
x!{test_coverage_report_generate}
x!{watch_and_reload}
x!{workspace}
x!{workspace_analysis}
x!{workspace_interface}
x!{consolidate_crate_interface}
x!{consolidated_crate_interface}
x!{extract_docs_from_ast_node}
x!{generate_signature_for_ast_node}
x!{crate_interface_item}
x!{public}
