[[bin]]
name = "workspacer-ensure-all-source-files-are-registered"
path = "src/bin/ensure_all_source_files_are_registered.rs"

[dependencies.derive_builder]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.1"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.1"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[dependencies.workspacer-git]
path = "../workspacer-git"
version = "0.1.1"

[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
version = "0.1.2"

[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.1"

[package]
categories = [
    "development-tools",
    "parsing",
    "asynchronous",
    "compilation",
    "utilities",
]
description = "Utility crate to ensure all source files are registered within a workspace, managing macro definitions and integration for seamless Rust project maintenance."
edition = "2024"
keywords = [
    "macro",
    "workspace",
    "source-files",
    "register",
    "rust",
]
name = "workspacer-register"
version = "0.1.2"
