[dependencies]
derive_builder.workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-git]
path = "../workspacer-git"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[package]
edition = "2024"
name = "workspacer-register"
version = "0.1.0"
description = "Utility crate to ensure all source files are registered within a workspace, managing macro definitions and integration for seamless Rust project maintenance."
keywords = ["macro", "workspace", "source-files", "register", "rust"]
categories = ["development-tools", "parsing", "asynchronous", "compilation", "utilities"]
[[bin]]
path = "src/bin/ensure_all_source_files_are_registered.rs"
name = "workspacer-ensure-all-source-files-are-registered"
