[package]
name = "rand-construct"
version = "0.10.0"
edition = "2021"

authors       = [ "klebs tpk3.mx@gmail.com" ]
description   = "Encapsulates the random-constructible and random-constructible-derive crates which are used for creating random instances of data structures with weighted probabilities"
license       = "Apache-2.0"
repository    = "https://github.com/klebs6/klebs-general"
homepage      = "https://github.com/klebs6/klebs-general"
documentation = "https://docs.rs/random-constructible-derive"
readme        = "README.md"
keywords      = ["randomness", "enums", "simulation", "ergonomics"]
categories    = ["game-development", "simulation", "rust-patterns"]

[dependencies]
once_cell = "1.16"
#random-constructible        = "0.10.0"
#random-constructible-derive = "0.10.0"
random-constructible        = { version = "*", path = "../random-constructible" }
random-constructible-derive = { version = "*", path = "../random-constructible-derive" }
