[dependencies]
derive_builder.workspace = true
getset.workspace = true

[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.0"
[dependencies.batch-mode-batch-client]
path = "../batch-mode-batch-client"
version = "0.2.0"
[dependencies.batch-mode-batch-index]
path = "../batch-mode-batch-index"
version = "0.2.0"
[dependencies.batch-mode-batch-metadata]
path = "../batch-mode-batch-metadata"
version = "0.2.0"
[dependencies.batch-mode-batch-reconciliation]
path = "../batch-mode-batch-reconciliation"
version = "0.2.0"
[dependencies.batch-mode-batch-schema]
path = "../batch-mode-batch-schema"
version = "0.2.0"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
version = "0.2.0"
[dependencies.batch-mode-json]
path = "../batch-mode-json"
version = "0.2.0"
[dependencies.batch-mode-batch-workspace]
path = "../batch-mode-batch-workspace"
version = "0.2.0"
[dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.2.0"
[package]
edition = "2024"
name = "batch-mode-batch-executor"
version = "0.2.0"
description = "Provides functionality for executing and managing batch processing workflows, including file management, status monitoring, error handling, and output reconciliation in OpenAI batch operations."
authors = ["klebs tpk3.mx@gmail.com"]
license = "MIT"
repository = "https://github.com/klebs6/klebs-general"
