[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[package]
edition = "2024"
name = "workspacer-check-private"
version = "0.1.0"