[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[package]
edition = "2024"
name = "workspacer-check-private"
version = "0.1.0"
description = "Ensures that a Rust crate is not marked as private before cargo publish, leveraging the async programming capabilities of Rust 2024 edition."
keywords = ["cargo", "publishing", "crate", "private", "asynchronous"]
categories = ["development-tools", "asynchronous", "config", "rust-patterns", "automation"]
