[dependencies]
workspacer-3p = { version = "0.5.0", path = "../workspacer-3p" }
derive_builder = "*"

[package]
name        = "workspacer-syntax"
version     = "0.5.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A crate for extracting documentation, checking public visibility, and generating signatures from Rust AST nodes as part of the Workspacer suite."
license     = "MIT OR Apache-2.0"
