[dependencies]
workspacer-3p = { version = "0.5.0", path = "../workspacer-3p" }
derive_builder.workspace = true

[package]
name        = "workspacer-syntax"
version     = "0.5.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "Generate and rehydrate Rust code signatures from AST nodes, supporting functions, structs, enums, traits, type aliases, and macros."
license     = "MIT OR Apache-2.0"
keywords = ["syntax", "signature", "AST", "code-generation", "rust"]
categories = ["parsing", "development-tools", "code-generation"]
