[dependencies.derive_builder]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[package]
authors = ["klebs tpk3.mx@gmail.com"]
categories = [
    "parsing",
    "development-tools",
]
description = "Generate and rehydrate Rust code signatures from AST nodes, supporting functions, structs, enums, traits, type aliases, and macros."
edition = "2024"
keywords = [
    "syntax",
    "signature",
    "AST",
    "code-generation",
    "rust",
]
license = "MIT OR Apache-2.0"
name = "workspacer-syntax"
repository = "https://github.com/klebs6/klebs-general"
version = "0.5.1"
