[dependencies.serde]
features = [ "derive" ]
version = "*"
[dependencies.serde_derive]
version = "*"
[dependencies.serde_json]
version = "*"
[package]
edition = "2024"
name = "ai-json-template"
version = "0.1.0"
