[dependencies]
indoc.workspace        = true
serde.workspace        = true
serde_derive.workspace = true
serde_json.workspace   = true
export-magic.workspace = true

[dependencies.save-load-traits]
path = "../save-load-traits"

[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "Contains code we use for ai-assisted struct generation. Please also see the ai-json-template-derive crate for more information."
edition = "2024"
license = "MIT"
name = "ai-json-template"
repository = "https://github.com/klebs6/klebs-general"
version = "0.1.0"
