[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.1"

[dependencies.derive_builder]
workspace = true

[dependencies.getset]
workspace = true

[dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.2.1"

[dependencies.serde]
workspace = true

[dependencies.serde_derive]
workspace = true

[dependencies.serde_json]
workspace = true

[package]
authors = ["klebs tpk3.mx@gmail.com"]
description = "Handles camel case tokens with optional comments and provides utilities for parsing token files and extracting JSON fields."
edition = "2024"
license-file = "OGPv1"
name = "camel-case-token-with-comment"
repository = "https://github.com/klebs6/klebs-general"
version = "0.2.1"
