[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.0"

[dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.2.0"

[package]
edition     = "2024"
name        = "camel-case-token-with-comment"
version     = "0.2.0"
description = "Handles camel case tokens with optional comments and provides utilities for parsing token files and extracting JSON fields."
authors     = ["klebs tpk3.mx@gmail.com"]
license     = "MIT"
repository  = "https://github.com/klebs6/klebs-general"
