[dependencies]
derive_builder.workspace = true
structopt.workspace      = true
serde.workspace          = true
serde_derive.workspace   = true
serde_json.workspace     = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-config]
path = "../workspacer-config"
version = "0.1.0"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
version = "0.5.0"
[dependencies.workspacer-consolidate]
path = "../workspacer-consolidate"
version = "0.5.0"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.0"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.0"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.0"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
version = "0.1.0"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.0"
[package]
edition = "2024"
name = "workspacer-readme-writer"
version = "0.1.0"
description = "Automates the generation of README.md and Cargo.toml fields using AI to enhance documentation quality in Rust projects."
keywords = ["README automation", "Rust crates", "AI-assisted documentation", "Cargo.toml management", "language models"]
categories = ["development-tools", "rust-patterns", "language-bindings", "async-io", "no-std"]

[[bin]]
path = "src/bin/readme_writer.rs"
name = "workspacer-readme-writer"
