[dependencies]
derive_builder.workspace = true
structopt.workspace      = true
serde.workspace          = true
serde_derive.workspace   = true
serde_json.workspace     = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-config]
path = "../workspacer-config"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[dependencies.workspacer-consolidate]
path = "../workspacer-consolidate"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-readme-writer"
version = "0.1.0"

[[bin]]
path = "src/bin/readme_writer.rs"
name = "workspacer-readme-writer"
