[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.batch-mode-process-response]
path = "../batch-mode-process-response"
[dependencies.batch-mode-batch-client]
path = "../batch-mode-batch-client"
[dependencies.batch-mode-batch-executor]
path = "../batch-mode-batch-executor"
[dependencies.batch-mode-batch-index]
path = "../batch-mode-batch-index"
[dependencies.batch-mode-batch-metadata]
path = "../batch-mode-batch-metadata"
[dependencies.batch-mode-batch-reconciliation]
path = "../batch-mode-batch-reconciliation"
[dependencies.batch-mode-batch-schema]
path = "../batch-mode-batch-schema"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
[dependencies.batch-mode-batch-workspace]
path = "../batch-mode-batch-workspace"
[dependencies.batch-mode-batch-workspace-interface]
path = "../batch-mode-batch-workspace-interface"
[dependencies.batch-mode-json]
path = "../batch-mode-json"
[dependencies.camel-case-token-with-comment]
path = "../camel-case-token-with-comment"
[dependencies.save-load-traits]
path = "../save-load-traits"
[dependencies]
structopt = "*"
[package]
edition = "2024"
name = "batch-mode"
version = "0.1.0"

[[bin]]
path = "src/bin/batch-mode-parse-raw-batch-file-dir.rs"
name = "batch-mode-parse-raw-batch-file-dir"

[[bin]]
path = "src/bin/camel_case_token_file_difference.rs"
name = "camel-case-token-file-difference"
