[dependencies]
async-trait.workspace       = true
named-item.workspace        = true
named-item-derive.workspace = true
unsafe-erased.workspace     = true

[dependencies.hydro2-3p]
path    = "../hydro2-3p"
version = "0.1.0"

[dependencies.hydro2-operator]
path    = "../hydro2-operator"
version = "0.1.0"

[dependencies.hydro2-operator-derive]
path    = "../hydro2-operator-derive"
version = "0.1.0"

[package]
edition     = "2024"
name        = "hydro2-basic-operators"
version     = "0.1.0"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A collection of fundamental operators for the hydro2 network ecosystem."
readme      = "README.md"
license-file = "OGPv1"
