[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[package]
categories = [
    "version-control",
    "utilities",
    "software-development",
    "development-tools",
    "api-bindings",
]
description = "A Rust crate to streamline the creation and management of Git commits in applications, simplifying version control processes with easy-to-use abstractions."
edition = "2024"
keywords = [
    "git",
    "commit",
    "version-control",
    "rust",
    "programmatic",
]
name = "workspacer-git-commit"
version = "0.1.2"
