[dependencies]
derive_builder.workspace = true
getset.workspace         = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-crate-mock]
path = "../workspacer-crate-mock"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml]
path = "../workspacer-toml"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[dependencies.workspacer-toml-mock]
path = "../workspacer-toml-mock"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-workspace-mock"
version = "0.1.0"
description = "A flexible mock framework to simulate and test Rust workspace environments, supporting various configurations for testing."
keywords = ["rust", "workspace", "mock", "simulation", "testing"]
categories = ["development-tools", "simulation", "rust-patterns", "concurrency", "testing"]
