[dependencies]
derive_builder.workspace    = true
named-item.workspace        = true
named-item-derive.workspace = true

[dependencies.hydro2-3p]
path = "../hydro2-3p"
version = "0.1.0"
[dependencies.hydro2-basic-operators]
path = "../hydro2-basic-operators"
version = "0.1.0"
[dependencies.hydro2-network]
path = "../hydro2-network"
version = "0.1.0"
[dependencies.hydro2-operator]
path = "../hydro2-operator"
version = "0.1.0"
[package]
edition     = "2024"
name        = "hydro2-mock"
version     = "0.1.0"
repository  = "https://github.com/klebs6/klebs-general"
description = "Mock utility components for testing within the hydro2 network ecosystem."
readme      = "README.md"
license-file = "OGPv1"
