[dependencies]
derive_builder = "*"
named-item = "0.6.0"
named-item-derive = "0.2.0"
[dependencies.hydro2-3p]
path = "../hydro2-3p"
[dependencies.hydro2-async-scheduler]
path = "../hydro2-async-scheduler"
[dependencies.hydro2-basic-operators]
path = "../hydro2-basic-operators"
[dependencies.hydro2-network]
path = "../hydro2-network"
[dependencies.hydro2-operator]
path = "../hydro2-operator"
[package]
edition = "2024"
name = "hydro2-mock"
version = "0.1.0"
