[dependencies.serde]
features = [ "derive" ]
version = "*"
[dependencies.serde_derive]
version = "*"
[dependencies.serde_json]
version = "*"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[package]
edition = "2024"
name = "workspacer-crate-interface"
version = "0.1.0"