[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-docs"
version = "0.1.0"
description = "Provides an async interface to run `cargo doc` within Cargo workspaces, facilitating Rust documentation generation."
keywords = ["rust", "workspace", "documentation", "async", "cargo"]
categories = ["development-tools", "command-line-utilities", "async-execution", "rust-patterns"]
