[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.1"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.1"

[package]
categories = [
    "development-tools",
    "command-line-utilities",
    "async-execution",
    "rust-patterns",
]
description = "Provides an async interface to run `cargo doc` within Cargo workspaces, facilitating Rust documentation generation."
edition = "2024"
keywords = [
    "rust",
    "workspace",
    "documentation",
    "async",
    "cargo",
]
name = "workspacer-docs"
version = "0.1.1"
