[package]
name = "workspacer-either"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[dependencies]
workspacer-3p = { path = "../workspacer-3p" }
workspacer-crate = { path = "../workspacer-crate" }
workspacer-workspace = { path = "../workspacer-workspace" }
workspacer-errors = { path = "../workspacer-errors" }
