[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-check-crates-io]
path = "../workspacer-check-crates-io"
version = "0.1.0"
[dependencies.workspacer-check-private]
path = "../workspacer-check-private"
version = "0.1.0"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.0"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.0"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.0"
[dependencies.workspacer-toml]
path = "../workspacer-toml"
version = "0.5.0"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
version = "0.1.0"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.0"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
version = "0.1.0"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
version = "0.5.0"
[package]
edition = "2024"
name = "workspacer-check-publish-ready"
version = "0.1.0"
description = "A Rust crate providing async interfaces for checking if a workspace or crate is ready for publishing on crates.io, ensuring integrity, version validity, and readiness through comprehensive validation."
keywords = ["rust", "cargo", "publishing", "workspace", "validation"]
categories = ["development-tools", "command-line-utilities", "config"]
