[dependencies]
derive_builder.workspace     = true
getset.workspace             = true
export-magic.workspace       = true
proc-macro2.workspace        = true
quote.workspace              = true
traced-test.workspace        = true
tracing.workspace            = true
syn.workspace                = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true

[dependencies.batch-mode-3p]
path = "../batch-mode-3p"

[dependencies.save-load-traits]
path = "../save-load-traits"

[dev-dependencies]
trybuild.workspace    = true
async-trait.workspace = true
serde.workspace       = true
serde_json.workspace  = true

[lib]
proc-macro = true

[package]
authors     = ["klebs tpk3.mx@gmail.com"]
categories  = ["development-tools", "code-generation"]
description = "A procedural macro for deriving batch-oriented language model workflows using annotated client and workspace fields."
edition     = "2024"
keywords    = ["batch", "workflow", "proc-macro", "language-model"]
license     = "MIT"
name        = "language-model-batch-workflow-derive"
readme      = "README.md"
repository  = "https://github.com/klebs6/klebs-general"
version     = "0.1.0"

[dev-dependencies.batch-mode-batch-workflow]
path = "../batch-mode-batch-workflow"
[dev-dependencies.batch-mode-batch-workspace-interface]
path = "../batch-mode-batch-workspace-interface"
[dev-dependencies.camel-case-token-with-comment]
path = "../camel-case-token-with-comment"
