[dependencies]
derive_builder = "0.20.2"
getset = "0.1.4"
export-magic = "0.3.6"
proc-macro2 = "1.0"
quote = "1.0"
traced-test = { version = "1.0.2" }
tracing = { version = "0.1.41" }
tracing-setup = { version = "1.0.2" }
tracing-subscriber = { version = "0.3.19", features = [ "env-filter", "json" ] }

[dependencies.batch-mode-3p]
path = "../batch-mode-3p"

[dependencies.syn]
features = [ "full" ]
version = "1.0"

[dev-dependencies]
trybuild = "1.0"
async-trait = "0.1.86"
[lib]
proc-macro = true
[package]
edition = "2024"
name = "language-model-batch-workflow-derive"
version = "0.1.0"

[dev-dependencies.batch-mode-batch-workflow]
path = "../batch-mode-batch-workflow"
