[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.batch-mode-batch-executor]
path = "../batch-mode-batch-executor"
[dependencies.batch-mode-batch-index]
path = "../batch-mode-batch-index"
[dependencies.batch-mode-batch-reconciliation]
path = "../batch-mode-batch-reconciliation"
[dependencies.batch-mode-batch-schema]
path = "../batch-mode-batch-schema"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
[dependencies.batch-mode-batch-workspace-interface]
path = "../batch-mode-batch-workspace-interface"
[dependencies.batch-mode-json]
path = "../batch-mode-json"
[dependencies.camel-case-token-with-comment]
path = "../camel-case-token-with-comment"
[package]
edition = "2024"
name = "batch-mode-process-response"
version = "0.1.0"
description = "Handles batch responses, errors, and JSON repairs in a batch processing system."
authors = ["klebs tpk3.mx@gmail.com"]
license = "MIT"
repository = "https://github.com/klebs6/klebs-general"
