[dependencies]
async-trait = "*"
derive_builder = "*"
disable_macro = "*"
erased = "*"
error-tree = "*"
export-magic = "*"
getset = "*"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
unsafe-erased = "*"
[dependencies.hydro2-3p]
path = "../hydro2-3p"
[dependencies.traced-test]
version = "*"
[dependencies.tracing]
version = "*"
[dependencies.tracing-setup]
version = "*"
[dependencies.tracing-subscriber]
features = [ "env-filter", "json" ]
version = "*"
[dev-dependencies]
async-trait = "*"
named-item = "0.6.0"
named-item-derive = "0.2.0"
trybuild = "*"
[dev-dependencies.hydro2-basic-operators]
path = "../hydro2-basic-operators"
version = "*"
[dev-dependencies.hydro2-operator]
path = "../hydro2-operator"
version = "*"
[dev-dependencies.hydro2-operator-derive]
path = "../hydro2-operator-derive"
version = "*"
[dev-dependencies.tokio]
features = [ "full" ]
version = "*"
[lib]
proc-macro = true
[package]
edition = "2024"
name = "hydro2-network-wire-derive"
version = "0.1.0"
