[dependencies]
structopt.workspace = true

[dependencies.generate-report-trait]
path = "../generate-report-trait"
version = "0.1.0"
[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
version = "0.1.0"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-add-new-crate-to-workspace]
path = "../workspacer-add-new-crate-to-workspace"
[dependencies.workspacer-analysis]
path = "../workspacer-analysis"
[dependencies.workspacer-check-publish-ready]
path = "../workspacer-check-publish-ready"
[dependencies.workspacer-cleanup]
path = "../workspacer-cleanup"
[dependencies.workspacer-consolidate]
path = "../workspacer-consolidate"
version = "0.5.0"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.0"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-detect-circular-deps]
path = "../workspacer-detect-circular-deps"
[dependencies.workspacer-docs]
path = "../workspacer-docs"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-git]
path = "../workspacer-git"
[dependencies.workspacer-interface]
path = "../workspacer-interface"
version = "0.5.0"
[dependencies.workspacer-linting]
path = "../workspacer-linting"
[dependencies.workspacer-metadata]
path = "../workspacer-metadata"
[dependencies.workspacer-name-all-files]
path = "../workspacer-name-all-files"
[dependencies.workspacer-pin]
path = "../workspacer-pin"
[dependencies.workspacer-publish]
path = "../workspacer-publish"
[dependencies.workspacer-rebuild-or-test]
path = "../workspacer-rebuild-or-test"
[dependencies.workspacer-syntax]
path = "../workspacer-syntax"
[dependencies.workspacer-test-coverage]
path = "../workspacer-test-coverage"
[dependencies.workspacer-toml]
path = "../workspacer-toml"
version = "0.5.0"
[dependencies.workspacer-watch-and-reload]
path = "../workspacer-watch-and-reload"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "A Rust crate providing extended interfaces for workspaces and crates, facilitating modular and reusable code development."
edition = "2024"
license = "MIT OR Apache-2.0"
name = "workspacer"
repository = "https://github.com/klebs6/klebs-general"
version = "0.6.0"
keywords = ["workspace", "crate", "interface", "development", "rust"]
categories = ["development-tools", "rust-patterns", "project-management", "api-bindings", "library"]
[[bin]]
name = "ws"
path = "src/bin/workspacer.rs"
