[dependencies]
workspacer-interface       = { version = "0.1.0", path = "../workspacer-interface" }
workspacer-3p              = { version = "0.1.0", path = "../workspacer-3p" }
workspacer-crate           = { version = "0.1.0", path = "../workspacer-crate" }
generate-report-trait      = { version = "0.1.0", path = "../generate-report-trait" }
lightweight-command-runner = { version = "0.1.0", path = "../lightweight-command-runner" }

[package]
name        = "workspacer"
version     = "0.2.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "An asynchronous workspace management library for Rust projects, providing utilities for automation, analysis, and maintenance of multi-crate workspaces."
license     = "MIT OR Apache-2.0"
