[package]
name = "json-repair"
version = "0.4.0"
edition = "2021"

description = "A well tested crate for repairing malformed JSON strings and repairing/parsing them into valid JSON values"
authors = [ "klebs tpk3.mx@gmail.com" ]
license = "MIT"
keywords = ["json", "repair", "parsing", "text", "serde"]
repository = "https://github.com/klebs6/klebs-general"
categories = ["development-tools"]

[dependencies]
export-magic       = "0.3.6"
json5              = "0.4.1"
serde              = { version = "1.0", features = ["derive"] }
serde_json         = "1.0"
error-tree         = "0.6.0"
tracing            = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "std", "env-filter"] }
traced-test        = "1.0.2"
tracing-setup      = "1.0.2"
regex              = "1.11.1"
