[dependencies]
derive_builder.workspace = true
getset.workspace         = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.0"
[dependencies.workspacer-toml]
path = "../workspacer-toml"
version = "0.5.0"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
version = "0.1.0"
[package]
edition = "2024"
name = "workspacer-toml-mock"
version = "0.1.0"
description = "A Rust library providing a fully functional mock implementation of CargoTomlInterface, simulating Cargo.toml behaviors for testing."
keywords = ["mock", "toml", "Cargo.toml", "testing", "simulation"]
categories = ["development-tools", "simulation", "parsing"]
