// ---------------- [ File: osx-wallpaper-cycler/src/lib.rs ]
#[macro_use] mod imports; use imports::*;

x!{apple_script_action_kind}
x!{applescript}
x!{build_dropbox_directory_cache_state}
x!{build_system_events_set_desktop_pictures_script}
x!{build_wallpaper_cache_assignments_for_desktop_targets}
x!{build_wallpaper_cache_state}
x!{cleanup_wallpaper_cache_files_not_in_use}
x!{compute_wallpaper_cache_path_for_remote}
x!{desktop_wallpaper_controller}
x!{dropbox_access_token_state}
x!{dropbox_api_client}
x!{dropbox_api_client_endpoints}
x!{dropbox_api_client_protocol_and_pagination_suite}
x!{dropbox_directory_cache_state}
x!{dropbox_directory_cache_usage_contract_suite}
x!{dropbox_endpoint_kind}
x!{dropbox_list_folder_failure_probe}
x!{dropbox_protocol_violation_detail}
x!{dropbox_wallpaper_candidate}
x!{dropbox_wallpaper_source}
x!{ensure_wallpaper_cache_dir_ready}
x!{escape_applescript_string}
x!{execute_applescript_via_nsapplescript}
x!{extract_dropbox_request_id_from_headers}
x!{file_system_operation_kind}
x!{infer_space_count_from_macos_spaces_defaults_json}
x!{initialize_tracing_subscriber_with_env_filter}
x!{load_dropbox_directory_cache_state_if_present}
x!{load_wallpaper_cache_state_if_present}
x!{load_wallpaper_rotator_config}
x!{macos_space_count_inference_contract_suite}
x!{mock_desktop_wallpaper_controller}
x!{mock_desktop_wallpaper_source}
x!{path_util}
x!{perform_wallpaper_rotation_cycle_once}
x!{persist_dropbox_directory_cache_state}
x!{persist_wallpaper_cache_state}
x!{query_desktop_count_via_system_events}
x!{run_wallpaper_rotation_daemon_loop}
x!{select_distinct_wallpapers_for_targets}
x!{set_desktop_pictures_via_system_events}
x!{switch_space}
x!{system_events_applescript_script_generation_suite}
x!{try_extract_applescript_error_number}
x!{try_infer_space_count_via_defaults_export_plutil}
x!{wallpaper_cache_assignment}
x!{wallpaper_cache_state}
x!{wallpaper_rotation_cycle_orchestration}
x!{wallpaper_rotator_cache_contract_suite}
x!{wallpaper_rotator_cli}
x!{wallpaper_rotator_config}
x!{wallpaper_rotator_config_toml}
x!{wallpaper_rotator_configuration_contract_suite}
x!{wallpaper_rotator_error}
x!{wallpaper_rotator_errors}
x!{wallpaper_rotator_invalid_configuration_details}
x!{wallpaper_rotator_launch_agent_plist_template}
x!{wallpaper_rotator_scope}
x!{is_process_trusted}
x!{set_desktop_pictures_across_spaces_via_system_events_by_switching}
x!{try_read_desktop_count_override_from_env}
