[dependencies.get-file-size]
path = "../get-file-size"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-analysis"
version = "0.1.0"
description = "Asynchronous Rust crate for detailed analysis of workspace file metrics, including sizes, lines of code, and file counts across crates."
keywords = ["workspace", "analysis", "rust", "asynchronous", "metrics"]
categories = ["development-tools", "asynchronous", "data-structures", "parsing", "science"]
