[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.0"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.0"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.0"
[package]
categories = [ "development-tools", "concurrency", "linting", "command-line-utilities", "asynchronous" ]
description = "Async Rust crate for linting workspaces using cargo clippy, capturing detailed reports and converting them to structured errors."
edition = "2024"
keywords = [ "rust", "linting", "cargo", "clippy", "asynchronous" ]
name = "workspacer-linting"
version = "0.1.0"