[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-linting"
version = "0.1.0"
description = "Async Rust crate for linting workspaces using cargo clippy, capturing detailed reports and converting them to structured errors."
keywords = ["rust", "linting", "cargo", "clippy", "asynchronous"]
categories = ["development-tools", "concurrency", "linting", "command-line-utilities", "asynchronous"]
