pub const LICENSE_TEXT: &'static str = r#"
Street Performer Protection License (SPPL) v1.0 Preamble:

This Street Performer Protection License is designed for software that generates
creative content (for example, generative systems). It allows broad freedom to
use, modify, and integrate such software, while protecting the outputs it
creates from unfettered commercial exploitation. In essence, Set A works
(performances, commentary, and other transformative uses) are free of
restrictive conditions, Set B works (the actual outputs of the generator) remain
protected by this license even as they propagate through creative workflows, and
Set C works (larger software projects that merely use or link to the generator)
can be released under any license for their own components, with only the
generator’s outputs being subject to SPPL. This license grants you rights to use
the generator software and its generated content with minimal obligations like
attribution and a revenue cap for commercial use, ensuring small creators and
businesses can benefit freely up to a threshold, while larger-scale
commercialization requires a separate license. The sections below set out the
terms in detail.

Definitions.

1.1 “Licensed Material” (or “Generator”) means the software, program, or code
  distributed under this Street Performer Protection License that is designed to
  algorithmically generate content. This includes any generative content system
  (including but not limited to procedural content generators, and similar
  tools).

1.2 “Output” means any content, media, or material produced by the Licensed
  Material, either directly or indirectly. This includes text, images, data, or
  other results generated by the Licensed Material, as well as any
  modifications, adaptations, or derivative works of such generated content. All
  Outputs are considered derivative of the Licensed Material for the purposes of
  this License, regardless of whether such Outputs are produced in one step or
  via a chain of processes. (For example, if an Output from the Generator is
  used as input to another system which in turn produces further content, all
  such downstream content remains “Output” under this License via a directed
  acyclic graph of derivations.)

1.3 “Set A Works” (also “Fully Free Works”) means new works created that are
  inspired by or based on the Outputs or the Licensed Material but do not
  incorporate or include substantial portions of the actual Output. Set A Works
  are typically transformative in nature – for example, a live performance,
  commentary, critique, parody, or analysis of an Output, or any other use that
  does not reproduce the Output itself. Set A Works do not contain verbatim or
  close copies of the Output content; to the extent they may reference the
  Output, they do so only incidentally or as allowed under fair use or this
  License.

1.4 “Set B Works” (also “Protected Outputs”) means the Outputs themselves and
  any works that include, reproduce, or are derived from the Outputs (apart from
  Set A Works). In other words, any content that the Generator produces – and
  any further derivative works that incorporate those Outputs (in whole or part)
  – are Set B Works. These remain subject to the terms and conditions of this
  License, even when incorporated into or transformed by other projects or
  processes.

1.5 “Set C Works” (also “Combined Software”) means any larger work or software
  that combines, links to, integrates, or utilizes the Licensed Material (the
  Generator) as a component, along with other software, modules, or content not
  governed by this License. For example, if you write your own program that
  calls or includes the Generator to produce content, your program is a Set
  C Work.

1.6 “Licensor” means the copyright holder(s) or entity authorizing use of the
  Licensed Material under this License.

1.7 “Licensee” (or “You”) means any individual or legal entity exercising the
  permissions granted by this License.

1.8 “Revenue Threshold” means the maximum amount of net revenue per year that
  a Licensee may generate from use of Outputs before a separate commercial
  license is required. The default Revenue Threshold under this License is one
  hundred thousand United States Dollars (US $100,000) in aggregate net revenue
  per calendar year attributable to Licensee’s use of the Outputs. The Licensor
  may specify a different monetary threshold (or additional details, such as
  a different currency or period) by including a field in the Licensed
  Material’s metadata or documentation (for example, specifying
  sppl.revenue_threshold_usd = 100000 in a Cargo.toml, LICENSE.meta file, or
  similar configuration). If no such specification is provided by the Licensor,
  the default of $100,000 USD annual net revenue applies.

License Grants – Software (Generator).

2.1 Right to Use and Modify the Generator: Subject to the terms and conditions
  of this License, the Licensor hereby grants to You a worldwide, royalty-free,
  non-exclusive, perpetual (subject to termination provisions in Section 8)
  license to use, reproduce, install, run, and modify the Licensed Material (the
  Generator) for any purpose, including both non-commercial and commercial
  purposes, with no upfront fee. You may make private or internal use of the
  Generator without limitation (aside from the output usage restrictions defined
  in this License).

2.2 Right to Distribute the Generator or Modified Versions: You may distribute
  the unmodified Licensed Material, or your modifications to it, or combinations
  of it with other software, in source or object code forms, provided that:

 (a) License Notice: You include a copy of this License (or a proper reference
to it) and the copyright notice with the distributed Generator code. Any
modified version of the Generator that You distribute must also be licensed
under this same SPPL v1.0 License (this ensures that the Generator and any
derivatives of its code remain under these terms). You must retain all notices
that refer to this License and to the absence of any warranty. You may add your
own copyright notices for your contributions, but you may not remove or alter
the Licensor’s copyright notices.

 (b) State of Source: If you distribute the Generator in an executable or
non-source form, you must make the corresponding source code available under
this License as well (for example, by providing a public repository link or
including the source in the distribution). This requirement only applies to the
Generator’s own source and modifications; it does not extend to other software
components that are merely combined with the Generator as explained in Section
2.4.

 (c) No Additional Restrictions on Generator: You may not impose any additional
legal restrictions or technological measures on the Generator software or its
source beyond those contained in this License. (For example, you cannot
distribute the Generator under this License but then require recipients to sign
a non-disclosure agreement for the Generator code – that would be an added
restriction.)

2.3 Patent License: If the Licensor owns patent rights that read on the
  Generator as released, the Licensor grants You a non-exclusive, worldwide,
  royalty-free patent license under those patents to use or implement the
  Generator as provided, or in any modifications You make, but solely to the
  extent necessary to use the Generator or make Set B Outputs as permitted by
  this License. This patent license terminates if You institute patent
  litigation against the Licensor or others over a patent claim that would be
  infringed by any use of the Generator.

2.4 Larger Works and Linking Exception (Set C): You are expressly allowed to
  combine the Generator with other software or modules (for example, by linking
  it as a library, or calling it from your software) to create a broader
  application or system. In such cases, only the Generator component (and its
  Outputs) are governed by this License. The broader application or parts of it
  that do not include or derive from the Generator code are not required to be
  licensed under SPPL. They may be under a different license of Your choice, as
  long as you comply with this License for the parts that are the Generator and
  its Outputs. To clarify: merely interfacing or integrating with the Generator
  does not subject your entire program to the SPPL, and this License does not
  claim rights over your original code that just uses the Generator. (However,
  any distribution of the Generator’s code itself, whether standalone or
  integrated, must follow Section 2.2 conditions, and any Outputs produced
  remain subject to Section 3.)

License Grants – Outputs (Set B).

3.1 Right to Use Outputs for Personal and Small-Scale Commercial Use: The
  Licensor grants You (as Licensee) a broad license to use, copy, modify, and
  create derivative works from the Outputs (Set B Works), subject to the
  restrictions in Section 4. This means You may freely utilize the content
  generated by the Generator in your own creative projects, include it in media,
  combine it with other content, and even exploit it commercially up to the
  limits defined by the Revenue Threshold (see Section 4.1). For example, you
  can incorporate Outputs into a game you are developing, publish a short story
  generated by the software, or use a generated image on your website, and you
  can earn money from these endeavors as long as your total net revenue from
  such uses remains below the threshold and you comply with attribution
  requirements.

3.2 Set A Works Are Unrestricted: If You create a work that is based on or
  inspired by an Output but qualifies as a Set A Work (fully free derivative as
  defined in Section 1.3) – for instance, a video of You performing a story
  generated by the software, or a critical commentary on a generated image
  – then, as a courtesy and clarification, the Licensor acknowledges that such
  a work is not considered a restricted Output under this License. Set A Works
  are not subject to the Revenue Threshold or other restrictions on Outputs;
  they are yours to use, share, or commercialize with no obligation under this
  License (except that if they do incidentally include excerpts of the Output,
  those excerpts might still invoke Output restrictions – use common sense: pure
  commentary or performance is free, but directly reproducing significant chunks
  of Output text or imagery in a new work would likely make it a Set
  B Work). This clause is intended to encourage commentary, criticism,
  education, or performance using the Outputs without fear of breaching the
  license – essentially treating such activities as fair and unrestricted uses.

3.3 Outputs Remain Licensed: Important – any Output (Set B Work) that You use or
  redistribute to others must remain subject to this same SPPL License,
  regardless of how far removed or transformed that Output becomes. In other
  words, if you share or distribute content that originated from the Generator,
  you must do so under the terms of this License (SPPL v1.0), ensuring that
  recipients of the content receive it with the same protections and
  restrictions. You agree not to attempt to re-license Outputs under different
  terms or claim proprietary rights in them that contradict this License. (This
  provision is what keeps the protective net over the Outputs: even if Outputs
  pass through multiple hands or systems, they carry this license forward in
  a chain or directed acyclic graph of derivations.)

Conditions and Limitations on Output Usage (Revenue Threshold & Commercial Use).

4.1 Revenue Threshold for Commercial Use: This License allows You to
  commercially use and profit from Outputs (Set B Works) up to the Revenue
  Threshold defined in Section 1.8. In practical terms, this means if You are an
  individual, a startup, or a small enterprise, you can monetize projects
  incorporating the Outputs – for example, selling a limited run of books
  containing generated stories, or earning advertising revenue from a website
  featuring generated content – until your total net revenue from those
  activities in a year reaches the Threshold. As long as your annual net revenue
  attributable to SPPL-covered Outputs stays below or equal to that Threshold,
  no additional permission or payment is needed beyond complying with this
  License’s terms.

4.2 Obligation Upon Exceeding Threshold: If your use of Outputs generates
  revenue beyond the Threshold in any given calendar year, you are required to
  obtain a separate commercial license from the Licensor to continue such
  use. Exceeding the Threshold without securing an appropriate commercial
  license from the Licensor within the grace period (see Section 8.2)
  constitutes a material breach of this License. In simpler terms, if your
  project using Outputs becomes very successful (earning above the set limit),
  you need to negotiate a commercial license or agreement with the Licensor to
  cover that high-level use. The Licensor is under no obligation by this License
  to grant such a commercial license – it will typically involve terms and fees
  to be agreed upon separately – but the SPPL gives you a chance and grace
  period to make that arrangement rather than immediately terminating your
  rights.

4.3 No Mass Redistribution or Rebranding of Outputs: Even within the Revenue
  Threshold, you may not engage in mass redistribution or wholesale
  commercialization of the Outputs in their original form. The Outputs are meant
  to be used as components of creative or productive works, not simply taken and
  sold as-is at scale. For example, you should not compile a large collection of
  raw Outputs and sell them as a competing product, or systematically rebrand
  and republish Outputs en masse under your own name or brand. Such activities
  fall outside the intended free use and would require explicit permission (a
  commercial license) from the Licensor regardless of revenue amount. In short,
  you can profit from using Outputs in your projects, but you cannot turn the
  Outputs themselves into a commercial product line or service without approval.

4.4 No Removal of License or Attribution: You must not remove, hide, or alter
  any license notices or embedded metadata in Outputs (if any) that indicate
  they are generated by the Licensed Material or subject to this License. Also,
  any distribution of Outputs must include a notice (in an appropriate manner)
  that the content was generated by software licensed under the SPPL v1.0. (This
  can often be satisfied by the Attribution requirement in Section 5, i.e.,
  a mention in the project’s README or documentation; a separate explicit tag on
  each Output is not required unless the format makes it easy to do so.)

Attribution Requirement (Minimal).

The only affirmative obligation when sharing or using the Generator or Outputs
publicly is to give attribution to the original Licensed Material and Licensor
in a reasonable way. This attribution requirement is intentionally minimal and
flexible:

For the Generator Software: If you distribute the Generator (modified or
unmodified) or include it in a larger project (Set C Work), you must ensure the
documentation or accompanying materials (such as a README, manual, or About
page) for your project includes a notice that the Generator is used and is
licensed under the “Street Performer Protection License (SPPL) v1.0”. If the
Licensor has provided a specific attribution text or name, include that as well
(for example, “This project includes the XYZ Generator (licensed under SPPL
v1.0)”).

For Outputs in Derivative Works: If you publish or share a work that
incorporates Outputs (Set B Works) – for example, a game containing generated
art, or a book of generated poetry – you must include in an appropriate place
(such as the acknowledgments, colophon, credits, or README) a statement that the
content includes material generated by [Name of Software, if given], licensed
under SPPL v1.0. You do not need to include this attribution on each individual
Output or overtly in the main creative content (no need for intrusive watermarks
or on-screen logos). A single mention in the project’s general documentation or
credits is sufficient.

Form of Attribution: The attribution should, at minimum, identify the Licensed
Material by name (if no specific name is given, you can refer to it as “the
generative software licensed under SPPLv1.0”), and refer to this license. For
example: “Portions of content generated by XYZ Generator © 2025 [Licensor Name],
used under the Street Performer Protection License 1.0.” If the Licensor’s name
is not provided, simply naming the software or repository is fine.

No Endorsement or Promotion: While giving attribution, you must not imply that
the Licensor endorses your use or your project. The attribution is a notice of
origin, not an advertisement.

No Burdensome Attribution Requirements: You are expressly NOT required to
display attribution in a manner that would be onerous or interfere with the user
experience of your work. For example, this License does not require pop-up
screens, splash screens, in-product logos, or constant on-screen
credits. A mention in documentation or standard credits suffices. Likewise, you
are not required to include the full license text alongside every Output; it’s
enough to include it once with your project or product documentation.

Additional Prohibited Uses.

This License is intended to be flexible and permissive for creative and
productive uses, with a focus on revenue threshold rather than enumerating usage
restrictions. However, to clarify intent, the following are not permitted under
this License (except with separate permission or license from the Licensor):

6.1 Large-Scale Commercial Exploitation Without License: Using the Outputs in
  a manner that generates revenue above the Threshold without obtaining
  a commercial license (per Section 4.2) is not permitted.

6.2 Reselling the Outputs as Standalone Products: You may not simply resell,
  license, or give away Outputs (unmodified or trivially modified) in bulk as
  the core of a commercial product or service. For instance, you cannot create
  a stock content library or NFT collection comprised mainly of Outputs and sell
  access to it, unless expressly authorized by the Licensor.

6.3 Misrepresentation of Origin: You must not mislead others about the origin of
  the Outputs. Claiming that Outputs generated by the Licensed Material are
  entirely your own original creation, without any acknowledgment, is
  a misrepresentation. (Attribution per Section 5 satisfies the requirement to
  acknowledge origin.) You also must not remove watermarks or metadata that the
  Generator may include to signify content is machine-generated (except as
  needed for formatting, and only if you still provide attribution as required).

6.4 Unlawful Use: You may not use the Generator or Outputs in violation of
  applicable laws. This includes not using it for purposes that would violate
  export controls, or in ways that infringe others’ intellectual property rights
  beyond what this License permits (for example, you shouldn’t feed copyrighted
  material into the Generator in a way that violates fair use or applicable law,
  nor use Outputs to commit fraud or defamation). (This clause doesn’t limit any
  specific freedom granted; it’s a reminder that this License doesn’t immunize
  unlawful conduct.)

Disclaimer of Warranty and Liability.

7.1 No Warranty: THE LICENSED MATERIAL (THE GENERATOR) AND ANY OUTPUTS ARE
  PROVIDED “AS IS” AND WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER
  EXPRESS OR IMPLIED, to the maximum extent permitted by law. The Licensor and
  contributors do not warrant that the Generator will meet your requirements or
  that its operation or Outputs will be uninterrupted or error-free. All risk as
  to the quality and performance of the Generator and Outputs is with
  You. Should the Generator prove defective or the Outputs be undesirable, You
  assume the cost of all necessary servicing, repair, or correction.

7.2 Limitation of Liability: In no event and under no legal theory, whether in
  tort (including negligence), contract, or otherwise, shall the Licensor or any
  contributors to the Licensed Material be liable to You for any direct,
  indirect, special, incidental, or consequential damages, or any losses or
  costs arising from this License or the use of the Generator or Outputs, even
  if such party has been advised of the possibility of such damages. This
  includes, by way of illustration and not limitation, damages for lost profits,
  loss of goodwill, loss or corruption of data, work stoppage, computer failure
  or malfunction, or any and all other commercial damages or losses.

7.3 Exceptions: Some jurisdictions do not allow the exclusion of implied
  warranties or the limitation of liability for incidental or consequential
  damages, so the above disclaimers and limitations may not fully apply to
  You. In such jurisdictions, the Licensor’s liability and warranty shall be
  limited to the minimum extent permitted by law.

Termination and Enforcement.

8.1 Termination for Breach: If You violate any material term of this License,
  your rights under this License (both for the Generator and any Outputs) will
  terminate automatically. Material terms include (but are not limited to)
  exceeding the Revenue Threshold without obtaining a commercial license,
  failing to provide required attribution after being notified and given
  a chance to cure, or distributing Outputs under a different license. Upon
  termination, You must cease all use and distribution of the Generator and
  Outputs that are under this License. However, termination of your rights does
  not terminate the licenses of any recipients who have obtained Outputs or the
  Generator from You under this License, provided they remain in compliance.

8.2 Threshold Grace Period: In the specific case that You exceed the Revenue
  Threshold, this License provides a 90-day grace period before termination is
  enforced, to allow You to remedy the situation. That grace period works as
  follows: As soon as You realize (or are notified by the Licensor) that your
  cumulative net revenue from Outputs in a calendar year has exceeded the
  Threshold, You should promptly notify the Licensor and cease further
  commercialization above the Threshold. From the date of exceeding (or
  notification of exceeding) the Threshold, You have up to 90 calendar days to
  secure a separate commercial license from the Licensor or otherwise come to an
  agreement that covers your past and ongoing use of Outputs. During this 90-day
  period, provided you are acting in good faith to obtain a license, the
  Licensor agrees not to terminate this License solely due to the threshold
  breach. If a commercial license is secured within the grace period, your
  rights under this License continue uninterrupted (or are reinstated
  retroactively, if needed) for the Outputs as covered by that new agreement. If
  no commercial license is obtained by the end of the 90 days, all rights
  granted to You by this License automatically terminate on day 91 with respect
  to any Outputs (and the Generator itself) in use beyond the Threshold, and You
  must stop using and distributing those Outputs and the Generator. (For
  clarity: the grace period is not a right to continue exceeding the Threshold
  indefinitely for 90 days without consequence; it is a one-time window to cure
  the breach by getting a proper license. It does not apply to repeated or
  willful violations.)

8.3 Right to Injunctive Relief: Because unauthorized use of the Outputs beyond
  the license terms could cause irreparable harm to the Licensor’s rights (for
  example, mass unlicensed commercialization can undermine the value intended to
  be protected), You acknowledge that the Licensor shall have the right to seek
  injunctive or other equitable relief in addition to any other remedies
  available by law in the event of a breach.

8.4 Survival: Sections 5 (Attribution), 7 (Warranty and Liability),
  8 (Termination), 9 (General) and any other clauses which by their nature
  should survive, shall survive termination of this License.

Audit of Compliance.

9.1 Audit Rights: The Licensor (or a third-party auditor authorized by the
  Licensor) has the right, not more than once per year, upon reasonable prior
  notice to You, to request an audit or certification of your records and
  practices as directly related to your use of Outputs, solely to verify
  compliance with the Revenue Threshold and other terms of this License. This
  may include requesting documentation of revenues derived from projects
  involving Outputs. The Licensor shall bear its own costs of any audit. You
  agree to cooperate in good faith with such a request by providing relevant
  non-privileged financial records or statements necessary to verify whether
  your use is within the allowed scope.

9.2 Confidentiality of Records: Any financial or business information provided
  by You for the purposes of an audit shall be used only for verifying
  compliance under this License and shall be kept confidential by the Licensor
  or auditor, except as needed to enforce the License terms.

9.3 Notice and Cure: If an audit or your own disclosure indicates that You have
  exceeded the Revenue Threshold without a commercial license, the Licensor will
  inform You in writing. You will then have the opportunity to address the issue
  in line with Section 8.2 (90-day grace period) if not already invoked. If
  other non-compliance (unrelated to revenue) is discovered, the Licensor may
  give You written notice and a reasonable period (e.g., 30 days) to cure the
  violation if it is curable (for example, adding a missing attribution). If You
  cure the breach within the given period, then your rights under this License
  shall continue as if no breach occurred.

Miscellaneous.

10.1 No Waiver: Failure by the Licensor to enforce any term of this License in
   a particular instance shall not constitute a waiver of that term or of the
   License or of any subsequent breach of the same or any other term.

10.2 Severability: If any provision of this License is held to be invalid or
   unenforceable under applicable law, such provision shall be reformed to the
   minimum extent necessary to make it valid and enforceable, and the remaining
   provisions of this License shall remain in full force and effect. If such
   reformation is not possible, the provision shall be deemed excised from this
   License, and the rest of the License shall remain in effect.

10.3 No Endorsement: This License does not grant permission to use any trade
   names, trademarks, or service marks of the Licensor, except as required for
   reasonable and customary attribution. You may not publicly imply that your
   use of the Licensed Material or Outputs is endorsed or sponsored by the
   Licensor (except simply stating the fact that you are using the Licensed
   Material is permitted).

10.4 No Assignment: You may not assign or transfer this License (or any of the
   rights granted herein) to another party without the Licensor’s prior written
   consent, except as part of a permitted distribution of the Generator or
   Outputs as allowed above. Any attempted assignment contrary to this section
   is void.

10.5 Entire Agreement: This License constitutes the entire agreement between the
   Licensor and You with respect to the Licensed Material and Outputs,
   superseding any prior agreements or understandings (whether written or oral)
   concerning the subject matter. Any modifications to this License must be made
   in writing and agreed to by the Licensor.

10.6 Governing Law and Jurisdiction: This License shall be governed by and
   construed in accordance with the laws of the United States of America and the
   laws of the District of Columbia, excluding any conflicts-of-law principles
   that would direct the application of another jurisdiction’s laws. Unless
   otherwise agreed in writing for a particular dispute or as required by
   a mandatory law, any dispute arising out of or relating to this License
   (including any question regarding its existence, validity, or termination)
   shall be subject to the exclusive jurisdiction of the courts located in
   Washington, D.C., USA. You and the Licensor consent to the personal
   jurisdiction of such courts.

10.7 Authors and Contributors Not Liable: Any contributor to the Licensed
   Material who is not expressly identified as the Licensor is not a party to
   this License and has no liability for the Licensed Material or Outputs under
   this License. Such contributors are intended third-party beneficiaries to the
   protections of Sections 7 (Warranty/Liability) and shall also be given
   attribution as required by Section 5 when their contributions are included in
   the Generator.

Summary of Key Permissions (Non-Normative): This summary is provided for
convenience and does not form part of the binding license terms above. In case
of any conflict, the sections above prevail.

You can use, modify, and share the generator software freely (and even
commercially) as long as you keep it under this license and give a little
credit. You can include it in your own apps without having to open-source your
own code, and you can use the cool content it makes in your projects.

You can use the generated content (Outputs) however you want for personal,
educational, or creative projects. You can even make money from it – especially
if you’re a small creator or business – up to a generous yearly revenue limit
(default $100k USD, or more if the licensor set a higher number). This is meant
to let indie devs, artists, and small teams profit from their work without
hassle.

You must not take the generated content and resell or mass-distribute it as-is,
or strip away the origin info and claim it entirely as your own. Basically,
don’t just grab the Outputs and build a commercial empire on them without
talking to the licensor. If you hit it big and earn above the set limit with
a project heavily based on these Outputs, that’s great – just remember you’ll
need to obtain a commercial license at that point (and you’ll have a 90-day
window to sort that out).

Giving credit is easy: just mention somewhere (like a README or credits page)
that you used the generator and that it’s under this license. No need for
obnoxious logos or splash screens – a simple note is fine.

Performances, commentary, and other transformative works inspired by the outputs
are completely free of these restrictions. We want you to stream, critique,
parody, and otherwise engage with the content freely – those uses aren’t limited
by the license (just don’t verbatim republish a protected output without abiding
by the license).

The license includes a standard warranty disclaimer (it might not work
perfectly; don’t blame the licensor if something goes wrong) and a liability
limit (the licensor isn’t liable for damages).

The license is governed by Washington, DC law – mainly relevant if there’s
a serious dispute – but hopefully everyone plays nice and that never comes up!
Enjoy creating with the generator, and respect these terms to keep it fair for
everyone.
"#;
