[dependencies.derive_builder]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_derive]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[package]
categories = [
    "config",
    "filesystem",
    "asynchronous",
    "development-tools",
    "parsing",
]
description = "A Rust crate to manage and utilize workspace configuration data in `.ws` directories for local and global setups, focusing on file management and configuration handling."
edition = "2024"
keywords = [
    "workspace",
    "configuration",
    "TOML",
    "asynchronous",
    "file-management",
]
name = "workspacer-config"
version = "0.1.1"
license = "MIT"
