[package]
authors = ["klebs tpk3.mx@gmail.com"]
categories = [
    "development-tools",
    "data-structures",
    "parsing",
]
description = "A Rust crate defining a trait for generating reports with customizable output and error handling."
edition = "2024"
keywords = [
    "report",
    "trait",
    "generation",
    "interface",
    "error-handling",
]
license = "MIT OR Apache-2.0"
name = "generate-report-trait"
repository = "https://github.com/klebs6/klebs-general"
version = "0.1.1"
