[package]
name        = "generate-report-trait"
version     = "0.1.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A Rust crate defining a trait for generating reports with customizable output and error handling."
license     = "MIT OR Apache-2.0"
keywords = ["report", "trait", "generation", "interface", "error-handling"]
categories = ["development-tools", "data-structures", "parsing"]
