[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.batch-mode-batch-metadata]
path = "../batch-mode-batch-metadata"
[dependencies.batch-mode-batch-schema]
path = "../batch-mode-batch-schema"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
[dependencies.save-load-traits]
path = "../save-load-traits"
[package]
edition = "2024"
name = "batch-mode-batch-client"
version = "0.1.0"
