[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.1.0"
[dependencies.batch-mode-batch-metadata]
path = "../batch-mode-batch-metadata"
version = "0.1.0"
[dependencies.batch-mode-batch-schema]
path = "../batch-mode-batch-schema"
version = "0.1.0"
[dependencies.batch-mode-batch-triple]
path = "../batch-mode-batch-triple"
version = "0.1.0"
[dependencies.save-load-traits]
path = "../save-load-traits"
version = "0.1.0"
[package]
edition = "2024"
name = "batch-mode-batch-client"
version = "0.1.0"
description = "This crate provides a client for interacting with OpenAI's batch processing API, allowing you to manage and download batch files asynchronously. It offers functionality for managing batch statuses, uploading files, and retrieving results after batch processing."
authors = ["klebs tpk3.mx@gmail.com"]
license = "MIT"
repository = "https://github.com/klebs6/klebs-general"
