[dependencies.export-magic]
workspace = true

[dependencies.traced-test]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[package]
authors = ["klebs tpk3.mx@gmail.com"]
categories = [
    "concurrency",
    "asynchronous",
]
description = "This crate provides a way to synchronously run async code."
edition = "2024"
keywords = [
    "async",
    "command-runner",
    "tokio",
    "rust",
]
license = "MIT OR Apache-2.0"
name = "sync-run-async"
repository = "https://github.com/klebs6/klebs-general"
version = "0.1.1"
