[dependencies.derive_builder]
workspace = true

[dependencies.generate-report-trait]
path = "../generate-report-trait"
version = "0.1.2"

[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
version = "0.1.3"

[dependencies.tracing]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.2"

[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.2"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.2"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.2"

[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
version = "0.1.3"

[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
version = "0.5.2"

[package]
categories = [
    "development-tools",
    "asynchronous",
    "concurrency",
    "filesystem",
]
description = "Asynchronous Rust workspace management crate, facilitating crate discovery and manipulation in Rust workspaces with thread-safe operations."
edition = "2024"
keywords = [
    "rust",
    "workspace",
    "asynchronous",
    "concurrency",
    "filesystem",
]
license = "MIT"
name = "workspacer-workspace"
version = "0.1.2"
