[dependencies]
derive_builder.workspace = true

[dependencies.generate-report-trait]
path = "../generate-report-trait"
[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-workspace"
version = "0.1.0"
description = "Asynchronous Rust workspace management crate, facilitating crate discovery and manipulation in Rust workspaces with thread-safe operations."
keywords = ["rust", "workspace", "asynchronous", "concurrency", "filesystem"]
categories = ["development-tools", "asynchronous", "concurrency", "filesystem", "project-management"]
