[dependencies]
derive_builder = "*"
[dependencies.generate-report-trait]
path = "../generate-report-trait"
[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-workspace"
version = "0.1.0"
