[package]
name          = "north-america"
version       = "0.3.0"
edition       = "2021"
authors       = [ "klebs tpk3.mx@gmail.com" ]
license       = "MIT"
description   = "A Rust crate providing enums and conversions for North American countries and their subregions, analogous to asia, europe, south-america, and central-america crates."
readme        = "README.md"
repository    = "https://github.com/klebs6/klebs-general"
documentation = "https://docs.rs/north-america"
keywords      = ["north-america", "geography", "countries", "regions", "rust"]
categories    = ["internationalization"]

[dependencies]
usa           = "0.5.0"
abbreviation-trait = "0.1.0"
serde         = { version = "1.0", features = ["derive"] }
export-magic  = "0.3.6"
strum         = { version = "0.24", features = ["derive"] }
strum_macros  = "0.24"
serde_json    = { version = "1" }
thiserror     = "2.0.6"
once_cell     = "1.20.2"
country       = "0.5.0"
language-enum = "0.2.0"
error-tree    = "0.6.0"

[features]
serde_abbreviation = []
