[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[package]
categories = [
    "development-tools",
    "concurrency",
    "asynchronous",
    "logging",
    "performance",
]
description = "A tracing and diagnostic tool for monitoring workspace upgrade processes, leveraging Rust 2024 features for high efficiency and low-latency logging."
edition = "2024"
keywords = [
    "tracing",
    "workspace",
    "upgrade",
    "diagnostics",
    "rust2024",
]
name = "workspacer-upgrade-test-tracing"
version = "0.1.2"
license = "MIT"
