[dependencies.tracing]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.2"

[dependencies.workspacer-crate]
path = "../workspacer-crate"
version = "0.5.2"

[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.2"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.2"

[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.2"

[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
version = "0.5.2"

[package]
categories = [
    "development-tools",
    "rust-patterns",
    "concurrency",
    "asynchronous",
    "config",
]
description = "Facilitates adding internal dependencies between crates within a Cargo workspace asynchronously with `toml_edit` for robust dependency management."
edition = "2024"
keywords = [
    "workspace",
    "dependency",
    "cargo",
    "toml",
    "asynchronous",
]
license = "MIT"
name = "workspacer-add-internal-dep"
version = "0.1.3"
