[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-add-internal-dep"
version = "0.1.0"
description = "Facilitates adding internal dependencies between crates within a Cargo workspace asynchronously with `toml_edit` for robust dependency management."
keywords = ["workspace", "dependency", "cargo", "toml", "asynchronous"]
categories = ["development-tools", "rust-patterns", "concurrency", "asynchronous", "config"]
