[dependencies]
delegate = "0.10.0"
indoc = "2.0.3"
ra_ap_syntax = "0.0.237"
rand = "0.8.5"
rayon = "1.7.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "3.2"
toml = "0.5"
tracing = "0.1.37"
walkdir = "2.4.0"
[dependencies.rustc_lexer]
package = "ra-ap-rustc_lexer"
version = "0.10.0"
[dependencies.tracing-subscriber]
features = [ "env-filter", "std" ]
version = "0.3.17"
[package]
description = "simple crate -- lets us scan crate(s) for locally defined structs, enums, types, fns, and traits"
edition = "2021"
license = "MIT"
name = "scan-crate-for-typedefs"
readme = "README.md"
version = "0.8.1"
