[workspace]
members = ["aqua-resistor", "aqua-3p"]

[workspace.dependencies]
serde          = "*"
serde_derive   = "*"
chrono         = "*"
uuid           = "*"
getset         = "*"
derive_builder = "*"
export-magic   = "*"
