[dependencies.batch-mode-3p]
path = "../batch-mode-3p"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_derive = "1.0.218"
serde_json = "1.0.139"

[package]
authors     = ["klebs tpk3.mx@gmail.com"]
categories  = ["text-processing", "api-bindings"]
description = "Provides an enumeration of supported language model types, including serialization logic."
edition     = "2024"
keywords    = ["language-model", "enum", "serialization"]
license     = "MIT"
name        = "language-model-type"
readme      = "README.md"
repository  = "https://github.com/klebs6/klebs-general"
version     = "0.1.0"
