[dependencies.batch-mode-3p]
path = "../batch-mode-3p"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_derive = "1.0.218"
serde_json = "1.0.139"

[package]
edition = "2024"
name = "language-model-type"
version = "0.1.0"
