[dependencies.batch-mode-3p]
path = "../batch-mode-3p"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
serde_json = "*"

[package]
edition = "2024"
name = "language-model-type"
version = "0.1.0"
