[dependencies.tracing]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.2"

[dependencies.workspacer-consolidate]
path = "../workspacer-consolidate"
version = "0.5.3"

[package]
authors = ["YourName <you@example.com>"]
description = "todo: write a description here"
edition = "2024"
license = "MIT"
name = "workspacer-lossless-file"
version = "0.1.1"
