[dependencies]
export-magic = "*"
tokio        = { version = "1.40.0", features = ["full"] }

[package]
name        = "lightweight-command-runner"
version     = "0.1.0"
edition     = "2024"
authors     = ["klebs tpk3.mx@gmail.com"]
repository  = "https://github.com/klebs6/klebs-general"
description = "A lightweight asynchronous command execution library using Tokio."
license     = "MIT OR Apache-2.0"
