[dependencies]
derive_builder.workspace = true
serde.workspace          = true
serde_derive.workspace   = true
serde_json.workspace     = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-config]
path = "../workspacer-config"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-interface]
path = "../workspacer-interface"
version = "0.5.0"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "Efficiently manage and validate `Cargo.toml` files with field verification and asynchronous operations."
edition = "2024"
license = "MIT OR Apache-2.0"
name = "workspacer-toml"
repository = "https://github.com/klebs6/klebs-general"
version = "0.5.0"
keywords = ["Cargo.toml", "Rust", "validation", "TOML", "semver"]
categories = ["parsing", "development-tools", "filesystem", "config", "rust-patterns"]
