[dependencies.derive_builder]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_derive]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-config]
path = "../workspacer-config"
version = "0.1.1"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[dependencies.workspacer-interface]
path = "../workspacer-interface"
version = "0.5.2"

[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
version = "0.1.2"

[package]
authors = ["klebs tpk3.mx@gmail.com"]
categories = [
    "parsing",
    "development-tools",
    "filesystem",
    "config",
    "rust-patterns",
]
description = "Efficiently manage and validate `Cargo.toml` files with field verification and asynchronous operations."
edition = "2024"
keywords = [
    "Rust",
    "validation",
    "TOML",
    "semver",
]
license = "MIT OR Apache-2.0"
name = "workspacer-toml"
repository = "https://github.com/klebs6/klebs-general"
version = "0.5.1"
