[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-bump"
version = "0.1.0"
