[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[dev-dependencies.workspacer-crate-mock]
path = "../workspacer-crate-mock"
[dev-dependencies.workspacer-workspace-mock]
path = "../workspacer-workspace-mock"
[dev-dependencies.workspacer-toml-mock]
path = "../workspacer-toml-mock"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[package]
edition = "2024"
name = "workspacer-bump"
version = "0.1.0"
description = "A Rust crate to manage and increment semantic versions within a workspace with support for async version bumping and recursive downstream updates."
keywords = ["versioning", "semver", "workspace", "async", "dependency-management"]
categories = ["development-tools", "parser-implementations", "algorithms"]
