[package]
name = "workspacer-topo"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[dependencies]
workspacer-3p                   = { path = "../workspacer-3p" , version = "0.5.1" }
derive_builder.workspace        = true
getset.workspace                = true
workspacer-workspace            = { path = "../workspacer-workspace" , version = "0.1.1" }
workspacer-errors               = { path = "../workspacer-errors" , version = "0.1.1" }
workspacer-crate                = { path = "../workspacer-crate" , version = "0.5.1" }
workspacer-workspace-mock       = { path = "../workspacer-workspace-mock" , version = "0.1.1" }
workspacer-interface            = { path = "../workspacer-interface" , version = "0.5.2" }
workspacer-detect-circular-deps = { path = "../workspacer-detect-circular-deps" , version = "0.1.1" }
workspacer-crate-mock           = { path = "../workspacer-crate-mock" , version = "0.1.1" }
workspacer-mock                 = { path = "../workspacer-mock" , version = "0.5.1" }
