[package]
name = "random-constructible-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
once_cell = "1.16"
rand = "0.8"

[dev-dependencies]
trybuild = "1.0"
random-constructible = "*"
