[package]
name = "random-constructible-derive"
version = "0.11.0"
edition = "2021"

authors       = [ "klebs tpk3.mx@gmail.com" ]
description   = "Provides a derive macro for the random-constructible crate which is used for creating random instances of enums with weighted probabilities"
license       = "MIT OR Apache-2.0"
repository    = "https://github.com/klebs6/klebs-general"
homepage      = "https://github.com/klebs6/klebs-general"
documentation = "https://docs.rs/random-constructible-derive"
readme        = "README.md"
keywords      = ["randomness", "enums", "simulation", "ergonomics"]
categories    = ["game-development", "simulation", "rust-patterns"]

[lib]
proc-macro = true

[dependencies]
proc-macro2  = "1.0"
quote        = "1.0"
syn          = { version = "1.0", features = ["full"] }
once_cell    = "1.16"
rand         = "0.8"
export-magic = "0.3.6"
itertools    = "0.13.0"
traced-test               = "1.0.2"
getset = "0.1.5"
derive_builder = "0.20.2"
tracing                   = { version = "0.1.40", features = ["log"] }
tracing-setup             = "1.0.2"
tracing-subscriber        = { version = "0.3", default-features = false, features = ["fmt", "std", "env-filter", "json"] }

[dev-dependencies]
trybuild = "1.0"
random-constructible = "0.10.0"
#random-constructible = { version = "*", path = "../random-constructible" }
