[dependencies]
export-magic.workspace       = true
pretty_assertions.workspace  = true
tempfile.workspace           = true
error-tree.workspace         = true
json-repair.workspace        = true
tokio.workspace              = true
serde.workspace              = true
serde_derive.workspace       = true
async-trait.workspace        = true
serde_json.workspace         = true
traced-test.workspace        = true
tracing.workspace            = true
tracing-setup.workspace      = true
tracing-subscriber.workspace = true

[package]
authors     = [ "klebs tpk3.mx@gmail.com" ]
description = "Provides traits for saving and loading objects asynchronously to and from files and directories."
edition     = "2024"
license     = "MIT"
name        = "save-load-traits"
repository  = "https://github.com/klebs6/klebs-general"
version     = "0.2.0"
