[dependencies]
export-magic = "*"
pretty_assertions  = "*"
tempfile = "*"
error-tree   = "0.6.0"
json-repair  = "0.4.0"
tokio        = { version = "1", features = ["full"] }
[dependencies.serde]
features = [ "derive" ]
version = "*"
[dependencies.serde_derive]
version = "*"
[dependencies.async-trait]
version = "*"
[dependencies.serde_json]
version = "*"
[dependencies.traced-test]
version = "*"
[dependencies.tracing]
version = "*"
[dependencies.tracing-setup]
version = "*"
[dependencies.tracing-subscriber]
features = [ "env-filter", "json" ]
version = "*"
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "Provides traits for saving and loading objects asynchronously to and from files and directories."
edition = "2024"
license = "MIT"
name = "save-load-traits"
repository = "https://github.com/klebs6/klebs-general"
version = "0.2.0"
