[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.0"
[dependencies.batch-mode-json]
path = "../batch-mode-json"
version = "0.2.0"
[dependencies.serde]
features = [ "derive" ]
version = "*"
[dependencies.serde_derive]
version = "*"
[dependencies.async-trait]
version = "*"
[dependencies.serde_json]
version = "*"
[dependencies.traced-test]
version = "*"
[dependencies.tracing]
version = "*"
[dependencies.tracing-setup]
version = "*"
[dependencies.tracing-subscriber]
features = [ "env-filter", "json" ]
version = "*"
[package]
authors = [ "klebs tpk3.mx@gmail.com" ]
description = "Provides traits for saving and loading objects asynchronously to and from files and directories."
edition = "2024"
license = "MIT"
name = "save-load-traits"
repository = "https://github.com/klebs6/klebs-general"
version = "0.2.0"
