[dependencies.generate-report-trait]
path = "../generate-report-trait"
version = "0.1.0"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
version = "0.1.0"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.0"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
version = "0.1.0"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
version = "0.1.0"
[package]
categories = [ "development-tools", "testing", "automation", "command-line-utilities" ]
description = "Facilitates test execution with code coverage gathering for cargo workspaces using cargo-tarpaulin."
edition = "2024"
keywords = [ "testing", "code-coverage", "rust", "cargo", "tarpaulin" ]
name = "workspacer-test-coverage"
version = "0.1.0"