[package]
name = "aqua-resistor"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[dependencies]
aqua-3p                  = { path = "../aqua-3p" }
serde.workspace          = true
serde_derive.workspace   = true
derive_builder.workspace = true
getset.workspace         = true
