[package]
name = "credit-card"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[dependencies]
tktax-money.workspace = true
export-magic.workspace = true
