[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[package]
edition = "2024"
name = "workspacer-workspace-interface"
version = "0.1.0"