[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-toml-interface]
path = "../workspacer-toml-interface"
[package]
edition = "2024"
name = "workspacer-workspace-interface"
version = "0.1.0"
description = "A Rust crate offering asynchronous interfaces for sophisticated workspace and crate management, leveraging advanced concurrency and data handling patterns."
keywords = ["workspace", "interface", "concurrency", "async", "management"]
categories = ["concurrency", "asynchronous", "data-structures", "network-programming", "development-tools"]
