[dependencies]
serde.workspace        = true
serde_derive.workspace = true
serde_json.workspace   = true

[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[package]
edition = "2024"
name = "workspacer-toml-interface"
version = "0.1.0"
