[dependencies]
derive_builder = "*"
[dependencies.agent-coordinate]
path = "../agent-coordinate"
[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
[dependencies.batch-mode-batch-scribe]
path = "../batch-mode-batch-scribe"
[dependencies.batch-mode-token-expansion-step]
path = "../batch-mode-token-expansion-step"
[dependencies.batch-mode-token-expansion-traits]
path = "../batch-mode-token-expansion-traits"
[dependencies.language-model-type]
path = "../language-model-type"
[package]
edition = "2024"
name = "instructed-language-model-at-coordinate"
version = "0.1.0"