[dependencies.agent-coordinate]
path = "../agent-coordinate"
version = "0.1.1"

[dependencies.batch-mode-3p]
path = "../batch-mode-3p"
version = "0.2.1"

[dependencies.batch-mode-batch-scribe]
path = "../batch-mode-batch-scribe"
version = "0.1.5"

[dependencies.batch-mode-token-expansion-step]
path = "../batch-mode-token-expansion-step"
version = "0.1.1"

[dependencies.batch-mode-token-expansion-traits]
path = "../batch-mode-token-expansion-traits"
version = "0.1.1"

[dependencies.derive_builder]
workspace = true

[dependencies.language-model-type]
path = "../language-model-type"
version = "0.1.1"

[package]
categories = [
    "algorithms",
    "api-bindings",
    "parsing",
    "science",
    "data-structures",
]
description = "A Rust library that facilitates precise instructional communication with Language Models by using agent coordinates, emphasizing structured JSON outputs and avoiding vague language."
edition = "2024"
keywords = [
    "language-model",
    "coordinates",
    "instructions",
    "json-output",
    "precision",
]
license-file = "OGPv1"
name = "instructed-language-model-at-coordinate"
version = "0.1.1"
