[dependencies.lightweight-command-runner]
path = "../lightweight-command-runner"
[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[dev-dependencies.workspacer-mock]
path = "../workspacer-mock"
[package]
edition = "2024"
name = "workspacer-rebuild-or-test"
version = "0.1.0"
description = "Asynchronous Rust crate for rebuilding and testing crates and workspaces, with comprehensive logging and error handling."
keywords = ["rust", "async", "build", "test", "workspace"]
categories = ["development-tools", "asynchronous", "config"]
