[dependencies.workspacer-3p]
path = "../workspacer-3p"
[dependencies.workspacer-add-internal-dep]
path = "../workspacer-add-internal-dep"
[dependencies.workspacer-crate]
path = "../workspacer-crate"
[dependencies.workspacer-crate-interface]
path = "../workspacer-crate-interface"
[dependencies.workspacer-errors]
path = "../workspacer-errors"
[dependencies.workspacer-mock]
path = "../workspacer-mock"
[dependencies.workspacer-register-internal-crate-in-prefix-group]
path = "../workspacer-register-internal-crate-in-prefix-group"
[dependencies.workspacer-scan-for-prefix-groups]
path = "../workspacer-scan-for-prefix-groups"
[dependencies.workspacer-workspace]
path = "../workspacer-workspace"
[dependencies.workspacer-workspace-interface]
path = "../workspacer-workspace-interface"
[package]
edition = "2024"
name = "workspacer-add-new-crate-to-workspace"
version = "0.1.0"