[package]
name = "workspacer-run"
version = "0.1.0"
authors = ["YourName <you@example.com>"]
license = "MIT"
edition = "2024"
description = "todo: write a description here"

# keywords = []
# categories = []

[dependencies]
workspacer-3p = { path = "../workspacer-3p" , version = "0.5.1" }
workspacer-workspace = { path = "../workspacer-workspace" , version = "0.1.1" }
workspacer-crate = { path = "../workspacer-crate" , version = "0.5.1" }
workspacer-errors = { path = "../workspacer-errors" , version = "0.1.1" }
workspacer-git = { path = "../workspacer-git" , version = "0.1.1" }
