[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.0"
[package]
edition = "2024"
name = "workspacer-upgrade-test-suites"
version = "0.1.0"
description = "A robust framework for testing upgrade paths in Rust workspaces, ensuring compatibility and reliability during version transitions."
keywords = ["workspace", "upgrade", "testing", "compatibility", "automation"]
categories = ["development-tools", "rust-patterns", "testing"]
