[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[package]
categories = [
    "development-tools",
    "command-line-utilities",
    "data-structures",
    "parsing",
    "network-programming",
]
description = "Displays an intuitive dependency tree for Rust workspaces, enhancing dependency management and project structure understanding."
edition = "2024"
keywords = [
    "rust",
    "dependencies",
    "workspace",
    "visualization",
    "project-management",
]
name = "workspacer-show-dependency-tree"
version = "0.1.1"
license = "MIT"
