[dependencies.workspacer-3p]
path = "../workspacer-3p"
version = "0.5.1"

[dependencies.workspacer-errors]
path = "../workspacer-errors"
version = "0.1.1"

[package]
categories = [
    "development-tools",
    "parsing",
    "data-structures",
    "async",
    "filesystem",
]
description = "Asynchronously reads `Cargo.lock` to map crates to versions, supporting dependency management in Rust projects with detailed error handling."
edition = "2024"
keywords = [
    "Cargo.lock",
    "dependencies",
    "asynchronous",
    "versioning",
    "Rust",
]
name = "workspacer-lock"
version = "0.1.1"
